### ISSUE TITLE
unable to 'atomic images tag' a docker image into ostree storage - unhelpful error returned

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#1002]
Not sure if this is supported or not, but we should be error'ing out with something more helpful than what I observed:

```
# rpm -q atomic
atomic-1.17.1-4.fc25.x86_64
# atomic images list
   REPOSITORY                               TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   registry.fedoraproject.org/f25/cockpit   latest   40aaf4b46bdb   2017-04-21 02:45   429.17 MB      docker    

# atomic images tag --storage ostree registry.fedoraproject.org/f25/cockpit my.registry.local/f25/cockpit:latest
Argument 3 does not allow None as a value
# atomic --debug images tag --storage ostree registry.fedoraproject.org/f25/cockpit my.registry.local/f25/cockpit:latest
Namespace(_class=<class 'Atomic.tag.Tag'>, assumeyes=False, debug=True, func='tag_image', ignore=False, profile=False, src='registry.fedoraproject.org/f25/cockpit', storage='ostree', target='my.registry.local/f25/cockpit:latest')
Argument 3 does not allow None as a value
Traceback (most recent call last):
  File "/usr/bin/atomic", line 203, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.5/site-packages/Atomic/tag.py", line 32, in tag_image
    backend.tag_image(self.args.src, self.args.target)
  File "/usr/lib/python3.5/site-packages/Atomic/backends/_ostree.py", line 169, in tag_image
    return self.syscontainers.tag_image(src, dest)
  File "/usr/lib/python3.5/site-packages/Atomic/syscontainers.py", line 1784, in tag_image
    repo.transaction_set_ref(None, get_image_branch(dest), rev)
TypeError: Argument 3 does not allow None as a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 225, in <module>
    sys.exit(1)
SystemExit: 1
```

**Comment by baude** [comment]
Closing on @miabbott behalf.  Open if not satisfied.

**Comment by chuanchang** [comment]
[ajia@localhost atomic]$ git rev-parse HEAD
69f6d52370a55e20a596fc3b21ac23b3d05064c9

NOTE: remotely copy atomic source code to atomic host.

[root@atomic-host-test cloud-user]# docker images
REPOSITORY                              TAG                                                     IMAGE ID            CREATED             SIZE
dphillip/open-vm-tools-docker           extras-rhel-7.3-docker-candidate-91953-20170622194059   4971f12594e7        4 days ago          302.2 MB

[root@atomic-host-test atomic]# ./atomic --debug images tag --storage ostree dphillip/open-vm-tools-docker:extras-rhel-7.3-docker-candidate-91953-20170622194059 open-vm-tools
Namespace(_class=<class 'Atomic.tag.Tag'>, assumeyes=False, debug=True, func='tag_image', ignore=False, profile=False, src='dphillip/open-vm-tools-docker:extras-rhel-7.3-docker-candidate-91953-20170622194059', storage='ostree', target='open-vm-tools')
Cannot find image dphillip/open-vm-tools-docker:extras-rhel-7.3-docker-candidate-91953-20170622194059.
Traceback (most recent call last):
  File "./atomic", line 203, in <module>
    sys.exit(_func())
  File "/var/home/cloud-user/atomic/Atomic/tag.py", line 32, in tag_image
    raise ValueError("Cannot find image {}.".format(self.args.src))
ValueError: Cannot find image dphillip/open-vm-tools-docker:extras-rhel-7.3-docker-candidate-91953-20170622194059.

**Comment by yuqi-zhang** [comment]
@chuanchang that is the expected behaviour, no? (i.e. you still can't tag from docker->ostree but now it tells you that the image doesn't exist in the --storage you specified)

The command you want is probably `atomic pull --storage ostree docker:dphillip/open-vm-tools-docker:extras-rhel-7.3-docker-candidate-91953-20170622194059`
