### ISSUE TITLE
maybe atomic upload should be called atomic push

### ISSUE THREAD

**Issue by eparis** [projectatomic/atomic#103]
Docker has `docker push` which takes an image and pushes it to a remote repository. Atomic has `atomic upload` which takes and image and pushed it to a remote system. These operations seems very similar. Obviously there are differences, since one of them is `docker` and one of them is `atomic` but I think using `push` in both cases would give a slightly more consistent user experience.

**Comment by rtnpro** [comment]
:+1: with the above idea. I want to work on this issue.

Is there any other reason for justifying the use of ``upload`` instead of ``push``. ``push`` is also more consistent with VCS like ``git``, ``hg``.

**Comment by rhatdan** [comment]
I am fine with it.

**Comment by rhatdan** [comment]
Renamed.
