### ISSUE TITLE
No means to specify environment variable with `atomic run`

### ISSUE THREAD

**Issue by metmajer** [projectatomic/atomic#1051]
There doesn't seem to be a mechanism to provide environment variables to `atomic run`, which would be favorable in some cases. Is there any reason why there is no such option available (like `-e` with docker)? Cheers!

**Comment by rhatdan** [comment]
Any environment variable from your environment will get through to the RUN Command,  What did you have in mind?

**Comment by metmajer** [comment]
Thanks @rhatdan, this wasn't clear to me. Does that mean that I need to specify a placeholder for the variable in the `RUN` label, e.g.:

```
LABEL RUN='docker run ... -e MY_VAR="$MY_VAR" $IMAGE'
```

which would result in

```
MY_VAR=1 atomic run acmeco/acmepro
````

? Or is this totally not needed? If that's the case, is it safe to provide default values à la

```
-e MY_VAR="${MY_VAR:-false}"
```

? Cheers, Martin

**Comment by rhatdan** [comment]
Yes the default value is the way to go.  We also have --opt1, --opt2 and --opt3, although I like to discourage their use.  

This is my favorite solution
-e MY_VAR="${MY_VAR:-false}"

**Comment by metmajer** [comment]
Many thanks, this really helps! I would suggest to have this use case documented on the atomic run manpage.

**Comment by rhatdan** [comment]
Good idea, but patches are always welcome...

**Comment by rhatdan** [comment]
@ipbabble PTAL

**Comment by metmajer** [comment]
Sure, would love to submit a patch!

**Comment by ipbabble** [comment]
Will take a look.

**Comment by metmajer** [comment]
@ipbabble: I've just provided a PR

**Comment by ipbabble** [comment]
I just saw that.  :)

**Comment by rhatdan** [comment]
William we are missing some other man pages for atomic, if you are interested in doing your man page magic again.

**Comment by ipbabble** [comment]
Ack. I'm interested.
