### ISSUE TITLE
atomic run does not work on system containers?

### ISSUE THREAD

**Issue by carlpett** [projectatomic/atomic#1061]
Hi,
I'm trying to debug my first system container by running `atomic run --storage ostree myimage:tag /bin/bash`. However, this exits with an error `Args instance has no attribute 'system_package'`. This seems to come from [here](https://github.com/projectatomic/atomic/blob/c1912d506949298ea2e9690b95e1a5e9b8a809f4/Atomic/syscontainers.py#L335). As far as I can tell, `self.args` is set from [here](https://github.com/projectatomic/atomic/blob/91f1e1621d556702feb4957dc90364ff8b871e55/Atomic/backends/_ostree.py#L22), which does not set `system_package`. 

Am I using this wrong, or is this an error? Is there some better way to try out a system container under development? The labels and config.json.template file might take some trial and error to get right.

*EDIT:* Also, the `--display` flag does not seem to be honored with ostree? Or maybe it just fails to early to be called?

**Comment by rhatdan** [comment]
@giuseppe @baude PTAL.

**Comment by giuseppe** [comment]
System containers do not use "atomic run". The way to use them is through "atomic install" and "atomic uninstall". I was thinking of adding something similar for running arbitrary commands in a system container but for now I suggest to either modify manually the config.json file to specify your command (before systemctl start $service) or if it is possible to use directly "runc exec" to execute a command in an already running container.

**Comment by carlpett** [comment]
Ok, I was hoping that run would work to test it out, but then I will be testing out with `runc` instead (maybe there could be a somewhat friendlier error to indicate that what I was trying could never work?).

Thanks!

**Comment by carlpett** [comment]
@giuseppe Is there a better place to ask questions about how to build these containers than here? 
After tearing my hair out for a while, I finally found that system containers do not care about the `INSTALL` label, meaning my installation scripts do not run. So I could just skip being a system container, but non-system containers do not get the nice systemd integration, so instead I need to manage my own systemd files etc. Is there a middle road here?

**Comment by giuseppe** [comment]
Yes system containers do not use the INSTALL label as we are trying to achieve a more "controlled" installation to the host. The documentation on this part must be improved, in the meanwhile could you explain what/how would you like to install? For example system containers support copy of files to the host on installation by placing these files under /exports/hostfs. For example /exports/hostfs/foo/bar will be copied to the host as /foo/bar

**Comment by rhatdan** [comment]
Perhaps we should make atomic command says something if there is a INSTALL Label. Something like

INSTALL Label is ignored when using system containers.

**Comment by carlpett** [comment]
@giuseppe Ah, installation of files is the first piece of the puzzle, thanks! :) 

With all respect for the difficulty in keeping good and up-to-date docs, the current ones are a bit confusing, especially with regards to the difference between system containers and "normal" containers. For example, this line:
> Labels can influence how the atomic tool uses a system container
... links to [LABELS.md](https://github.com/projectatomic/atomic-system-containers/blob/master/LABELS.md) which lists the `install` label. That was what made me think they'd work together. 

The bigger picture goal is that I'm trying to build a container for a [Saltstack](https://github.com/saltstack/salt) minion. I'm not sure of the general stance to configuration management for Atomic is? I'm guessing it's closer to "just use cloud-init" rather than putting agents on the hosts? We have a pretty significant investment in Saltstack in our existing RHEL infrastructure, however, including using it for our PKI processes, so just switching to Ansible or such isn't really up as an option. Although, PKI and a handful of other files in /etc is probably all that we'll do with it. Bad idea?

**Comment by carlpett** [comment]
Ok, so I got this almost working now, thank you very much! Any plans to support templating files that are added to /exports/hostfs? At the moment I can wrap my executable with a script that does it, but having it set at install-time would seem nicer, to me at least.

**Comment by giuseppe** [comment]
you can specify them in the `/exports/manifest.json` file as:

```
        "installedFilesTemplate" : [
            "/usr/local/bin/hello-template.sh"
        ]
```

**Comment by carlpett** [comment]
Amazing, that was _exactly_ what I wanted! :)
