### ISSUE TITLE
Doesn't Atomic support corporate proxys?

### ISSUE THREAD

**Issue by ununseptium** [projectatomic/atomic#1068]
Hi there,
currently i'm trying to evaluate atomic hosts for our environment but i somehow cannot get this to work. 

I'm somewhat experienced with the usual docker proxy behavior and already tried adding the proxy info as a custom docker daemon environment variable, also added it to /etc/sysconfig/docker and even exporting HTTP_PROXY and HTTPS_PROXY doesn't work. 

It should be mentioned that adding the proxy infos to the subscription-manager's config file worked perfectly fine.

It's quite hard for me to even debug those things because i'm not really getting any helpful error messages and also can't find proper logs related to the atomic cli tool.

Is there anything atomic related that i'm missing?
Thanks in advance for any help <3

**Edit: Also i just confirmed that the default docker pull command works perfectly fine. So there's definitely something odd going on with the atomic cli.**

**Comment by baude** [comment]
could you try adding proxy information to /etc/atomic.conf?

**Comment by ununseptium** [comment]
Thanks for the quick response. I appreciate that. 
Besides the fact that it's super hard to search for that specific part of your documentation, i literally still can't find it on the projectatomic.io website nor on the redhat specific documentation pages, the proxy settings doesn't allow credentials as it seems.

The python error trace tells me that an unexpected : caused the crash which is a little unfortunate.

**Comment by baude** [comment]
at one point there was a typo in that file ... where a '=' should have been a ':'.  Any chance that might be the issue here? Also, if you want to interactively hack at this, i'm on freenode \#atomic as rangerpb.

**Comment by baude** [comment]
can this be closed now ?

**Comment by ununseptium** [comment]
Yes, but i hope the docs are going to be improved in the future ;D
