### ISSUE TITLE
Fix PEP8 warnings for codebase

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomic#115]
If ran PEP8 coding guidelines checker on code-base, it throws warnings.
Idea here is to fix those warnings and have code compliant with PEP8 coding guidelines.

Also should we add a gate for PEP8 check in the CI Job. @rhatdan : Thoughts?

**Comment by willmtemple** [comment]
> Also should we add a gate for PEP8 check in the CI Job.
 
+1

**Comment by rhatdan** [comment]
I agree. Lets add it to make test.
