### ISSUE TITLE
add support for `atomic mount --live` for overlayfs backend

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic#1153]
I understand this is just about writing the code for atomic, right? Or is there a technical reason why containers stored on overlayfs backend can't be mounted RW?

```
$ atomic mount --live something ./asd
The OverlayFS backend does not support live mounts.
```

**Comment by rhatdan** [comment]
Overlay does not allow the file system to be mounted in two places at the same time, is probably this issue.   @rhvgoyal WDYT
One thing we could do is what we are doing with buildah and kpod, is the mount command returns the mount point rather then the user specifying it.  This way we could just mount up the file system in the standard location, and return the path.

**Comment by TomasTomecek** [comment]
How about a bind-mount?

**Comment by rhatdan** [comment]
Yes that would work also.
