### ISSUE TITLE
enhancement: atomic containers update *

### ISSUE THREAD

**Issue by Firstyear** [projectatomic/atomic#1157]
Hi,

When updating an atomic host there are two parts that need updating. First the ostree (rpm-ostree update). The second is the running containers. Dockers update story for "updating from version A to B" in near impossible to find or access.

Atomic improves this greatly by providing an "atomic containers update <image>" command. This allows a docker image to be pulled and updated, and on container re-deployment/restart the new image is used. This is great for admins as it makes docker updates accessible.

However, the challenge is that you need to *name* the image you want to update. On an atomic host I may have 3 or 4 images present (perhaps more). And you may have many hosts, and during a patching/update cycle you don't want to try to hand-craft update commands for each host.

There should be an accessible way to "update all docker images" on the host. This likely will need to understand the deployed image names so that they can all be correctly updated.

This would enable admins to "atomic containes update" to patch all container images. Additionally, it could be integrated to the atomic upgrade command such as:

atomic upgrade -r --containers

To provide a complete patch for applications and host cycle, as well as reboot (and we all know automatic patching is a great thing!)

Thanks for considering this idea,

**Comment by rhatdan** [comment]
I think this is a good idea. but probably should have --all for the option.

@baude @giuseppe PTAL

**Comment by giuseppe** [comment]
this was just implemented:

https://github.com/projectatomic/atomic/pull/1136

We have an `atomic images update --all` to update all images, and `atomic containers --update` to update all the containers, it is targetting mainly system containers.

@Firstyear, could you verify with the last version from git if it works well with Docker?

**Comment by giuseppe** [comment]
`atomic images update --all --storage docker` works for me.  Although, Docker containers are not recreated and they will still use the old image.

For system containers we have `atomic containers update --all`, but that is easy to do since we know exactly how to run it.

Should this be done with Docker containers?  If so, how to update a container given an updated image pulled in the storage?  Only in the case UNINSTALL and INSTALL labels are present?

**Comment by giuseppe** [comment]
@Firstyear have you had a chance to look at it?

**Comment by giuseppe** [comment]
closing for now as I've not heard anything back.  Please feel free to reopen
