### ISSUE TITLE
Atomic install fails with AttributeError on Ubuntu

### ISSUE THREAD

**Issue by markdand** [projectatomic/atomic#1165]
Hi,

After following the installation documents for Debian, I get the following error when trying to run atomic install, using --debug

`'Namespace' object has no attribute 'system'
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/local/lib/python2.7/dist-packages/Atomic/install.py", line 110, in install
    str_backend = 'ostree' if self.args.system else self.args.storage or storage
AttributeError: 'Namespace' object has no attribute 'system'
`
Am I missing something?
Any assistance would be appreciated.

Thanks

**Comment by giuseppe** [comment]
It looks like you have not ostree installed, so the `self.args.system` is not set.

Could you verify if https://github.com/projectatomic/atomic/pull/1167 solves the problem for you?

**Comment by markdand** [comment]
Hi,

There is not longer a failure, however all the command does now is output 'Registries' and doesn't seem to perform any actions.

Here is the debug output
`Namespace(_class=<class 'Atomic.install.Install'>, args=['servername'], assumeyes=False, debug=True, display=False, func='install', ignore=False, image='projectatomic/atomic-registry-install', name=None, opt1=None, opt2=None, opt3=None, profile=False, storage=None)
'Registries'
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/local/lib/python2.7/dist-packages/Atomic/install.py", line 112, in install
    img_obj = be.has_image(self.args.image)
  File "/usr/local/lib/python2.7/dist-packages/Atomic/backends/_docker.py", line 112, in has_image
    name_search = util.image_by_name(img, images=image_info)
  File "/usr/local/lib/python2.7/dist-packages/Atomic/util.py", line 145, in image_by_name
    i_reg, i_rep, i_img, i_tag, _ = Decompose(img_name).all
  File "/usr/local/lib/python2.7/dist-packages/Atomic/util.py", line 968, in __init__
    self._decompose(input_name)
  File "/usr/local/lib/python2.7/dist-packages/Atomic/util.py", line 987, in _decompose
    if not is_network_address(reg):
  File "/usr/local/lib/python2.7/dist-packages/Atomic/util.py", line 975, in is_network_address
    if _input in [x['hostname'] for x in get_registries()]:
  File "/usr/local/lib/python2.7/dist-packages/Atomic/util.py", line 115, in get_registries
    search_regs = [x['Name'] for x in dconf['Registries']]
KeyError: 'Registries'
`

**Comment by giuseppe** [comment]
is Docker running?

**Comment by markdand** [comment]
Yes it is and this is the version `Docker version 17.06.2-ee-4, build dd2c358`

**Comment by giuseppe** [comment]
I see, it seems like "docker info" doesn't output Registries on a non Red Hat system.  I can try to setup a VM later, but in the meanwhile, does this patch work for you?

```
diff --git a/Atomic/util.py b/Atomic/util.py
index 67ec1b9..fc903e6 100644
--- a/Atomic/util.py
+++ b/Atomic/util.py
@@ -112,7 +112,7 @@ def get_registries():
             registries.append({'hostname': 'registry-1.docker.io', 'name': 'docker.io', 'search': True, 'secure': True})
     elif is_backend_available('docker'):
         dconf = get_docker_conf()
-        search_regs = [x['Name'] for x in dconf['Registries']]
+        search_regs = [x['Name'] for x in dconf['Registries']] if 'Registries' in dconf else ['docker.io']
         rconf = dconf['RegistryConfig']['IndexConfigs']
         # docker.io is special
         if 'docker.io' in rconf:
```

**Comment by markdand** [comment]
Thanks,
Applied the patch but now get a different error:
`Namespace(_class=<class 'Atomic.install.Install'>, args=['sahl-ubu07'], assumeyes=False, debug=True, display=False, func='install', ignore=False, image='projectatomic/atomic-registry-install', name=None, opt1=None, opt2=None, opt3=None, profile=False, storage=None)
'Namespace' object has no attribute 'system_package'
Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/local/lib/python2.7/dist-packages/Atomic/install.py", line 138, in install
    if self.args.system_package == 'build':
AttributeError: 'Namespace' object has no attribute 'system_package'`

**Comment by giuseppe** [comment]
I guess this was last tested on a non Red Hat system long time ago..

`--system-package` is used also for Docker, so it should not depend from OSTree:

```
diff --git a/Atomic/install.py b/Atomic/install.py
index c9a8c3c..98de130 100644
--- a/Atomic/install.py
+++ b/Atomic/install.py
@@ -65,8 +65,6 @@ def cli(subparser):
         system_xor_user.add_argument("--system", dest="system",
                                      action='store_true', default=False,
                                      help=_('install a system container'))
-        installp.add_argument("--system-package", dest="system_package", default="auto",
-                              help=_('control how to install the package.  It accepts `auto`, `yes`, `no`, `build`'))
         installp.add_argument("--runtime", dest="runtime", default=None,
                               help=_('specify the OCI runtime to use for system and user containers'))
         installp.add_argument("--rootfs", dest="remote",
@@ -77,6 +75,8 @@ def cli(subparser):
                               action='append',
                               help=_("specify a variable in the VARIABLE=VALUE "
                                      "form for a system container"))
+    installp.add_argument("--system-package", dest="system_package", default="auto",
+                          help=_('control how to install the package.  It accepts `auto`, `yes`, `no`, `build`'))
     installp.add_argument("args", nargs=argparse.REMAINDER,
                           help=_("additional arguments appended to the image "
                                  "install method"))
```

**Comment by rhatdan** [comment]
Upstream Docker does not support a list of registries to search, so this will not work.  atomic tool should be able to handle it.

**Comment by giuseppe** [comment]
@markdand https://github.com/projectatomic/atomic/pull/1171
