### ISSUE TITLE
Minor question about documentation

### ISSUE THREAD

**Issue by peterbaouoft** [projectatomic/atomic#1193]
In https://github.com/projectatomic/atomic/blob/master/docs/atomic-pull.1.md, we have the following documents. 
```
An 'ostree' image refers to an image which is fetched from a remote OSTree repository. The remote has to be already configured in the local OSTree repository:

atomic pull --storage ostree ostree:REMOTE/branch
```

But the code in syscontainers.py (shown below) seems otherwise. 
```
 def _pull_image_to_ostree(self, repo, image, upgrade, src_creds=None):
        if not repo:
            raise ValueError("Cannot find a configured OSTree repo")
        if image.startswith("ostree:") and image.count(':') > 1:
            self._check_system_ostree_image(repo, image, upgrade)
```

From tutorialspoint website https://www.tutorialspoint.com/python/string_count.htm, description of count
> The method count() returns the number of occurrences of substring sub in the range [start, end]

 In code, for "ostree image" we are expecting input to have at least 2 colons right? But in the doc, we said we are expecting a remote/branch? So, there seems to be a conflict here? Or I am misinterpreting it? Thanks in advance :-)!

**Comment by giuseppe** [comment]
I think this must be droppoed. We added `ostree:` for a way to pull images directly from another `ostree` repository but we never used it.  Today `ostree:` has a different meaning with what we are doing with Skopeo.  I've opened a PR here: https://github.com/projectatomic/atomic/pull/1197
