### ISSUE TITLE
atomic uninstall can not recognize container name properly

### ISSUE THREAD

**Issue by peterbaouoft** [projectatomic/atomic#1199]
Hi I am recently playing around with atomic uninstall command. I noticed this interesting behaviour. Looks like container name is not rendered properly with atomic uninstall? 
 
```
[root@localhost ~]# atomic images list
   REPOSITORY              TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   docker.io/hello-world   latest   f2a91732366c   2017-11-21 00:23   1.85 KB        docker    
   docker.io/hello-world   latest   8072a54ebb3b   2018-02-27 21:23   985.0 B        ostree    
[root@localhost ~]# atomic install --system --system-package=no docker.io/hello-world 
Extracting to /var/lib/containers/atomic/hello-world.0
Warning: /exports directory not found.  Default config files will be generated.
Warning: You may want to modify `/var/lib/containers/atomic/hello-world.0/config.json` before starting the service
systemctl daemon-reload
systemctl enable hello-world
[root@localhost ~]# atomic containers list                                         
   CONTAINER ID IMAGE                NAME       COMMAND    CREATED          STATE      BACKEND    RUNTIME   
   hello-world  docker.io/hello-worl hello-worl run.sh     2018-02-27 21:23 failed     ostree     /bin/runc
[root@localhost ~]# atomic uninstall --storage ostree docker.io/hello-world --name hello-world
[root@localhost ~]# ls /var/lib/containers/atomic/hello-world/     
config.json  hello-world.service  info  rootfs
```

In `_ostree` backend, it also looks like the container name did not get rendered?  WDYT
```
    def uninstall(self, iobject, name=None, **kwargs):
        return self.syscontainers.uninstall(iobject.name)
```

This is produced on Atomic Host:
```
[root@localhost ~]# rpm-ostree status
State: idle
Deployments:
* fedora-atomic:fedora/27/x86_64/atomic-host
                   Version: 27.60 (2018-01-16 16:35:15)
                BaseCommit: 972e5a8158b610fec80f3f73f3372b7bea2b841038f2e246aa7623dbf5b5a751
         PendingBaseCommit: 772ab185b0752b0d6bc8b2096d08955660d80ed95579e13e136e6a54e3559ca9
        PendingBaseVersion: 27.61 (2018-01-17 15:52:47)
              GPGSignature: Valid signature by 860E19B0AFA800A1751881A6F55E7430F5282EE4
           LayeredPackages: man

  fedora-atomic:fedora/27/x86_64/atomic-host
                   Version: 27.61 (2018-01-17 15:52:47)
                BaseCommit: 772ab185b0752b0d6bc8b2096d08955660d80ed95579e13e136e6a54e3559ca9
              GPGSignature: Valid signature by 860E19B0AFA800A1751881A6F55E7430F5282EE4
           LayeredPackages: man

```

**Comment by giuseppe** [comment]
we should error out here as well when `--name` is provided as system containers ignore it.

You need to use:

`atomic uninstall --storage ostree hello-world`

**Comment by peterbaouoft** [comment]
> You need to use:
atomic uninstall --storage ostree hello-world

Right, but the container name is different than the image name this case right?  and ... because how we did it in `uninstall.py`, we will first not find the image and exit before hand no?

**Comment by peterbaouoft** [comment]
PR in https://github.com/projectatomic/atomic/pull/1202

**Comment by giuseppe** [comment]
> Right, but the container name is different than the image name this case right? and ... because how we did it in uninstall.py, we will first not find the image and exit before hand no?

yes, but it is fine for system containers to have a different name than the image and we don't need to know what was the image of the container before uninstalling it.

That is why `atomic uninstall $NAME` is enough for system containers, we should only report an usage error when `--name` is used with system containers.

**Comment by peterbaouoft** [comment]
> That is why atomic uninstall $NAME is enough for system containers

Sorry, I don't think I fully understand this part. I think when you specify `atomic uninstall $NAME`, the system container(container in ostree backend) will be uninstalled if and only if the container has the same name with the image right?

The code in the uninstall.py is as the following: here, we are getting the image first, then we uninstall the container based on image name right? 
```
 beu = BackendUtils()
        try:
            be, img_obj = beu.get_backend_and_image_obj(self.args.image, str_preferred_backend=self.args.storage)
        except ValueError as e:
            if 'ostree' in [x().backend for x in beu.available_backends]:
                ost = OSTreeBackend()
                img_obj = ost.has_container(self.args.image)
                if not img_obj:
                    raise ValueError(e)
                be = ost
        be.uninstall(img_obj, name=self.args.name, atomic=self, ignore=self.args.ignore)
```

and in `_ostree.py` we have, which only uses image name right?: 
```
 def uninstall(self, iobject, name=None, **kwargs):
        return self.syscontainers.uninstall(iobject.name)
```

**Comment by peterbaouoft** [comment]
For instance, one example to demonstrate above case is the following:
```
[root@localhost ~]# atomic images list
   REPOSITORY              TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
>  docker.io/hello-world   latest   8072a54ebb3b   2018-02-27 21:23   985.0 B        ostree    
[root@localhost ~]# atomic containers list -a
   CONTAINER ID IMAGE                NAME       COMMAND    CREATED          STATE      BACKEND    RUNTIME   
   test_contain docker.io/hello-worl test_conta run.sh     2018-03-01 16:16 inactive   ostree     /bin/runc 
[root@localhost ~]# atomic uninstall --storage ostree hello-world
Unable to find 'hello-world' in the following backends: docker, ostree
[root@localhost ~]# atomic uninstall --storage ostree docker.io/hello-world
[root@localhost ~]# ls /var/lib/containers/atomic/                   
test_container_name  test_container_name.0
```

**Comment by giuseppe** [comment]
> Sorry, I don't think I fully understand this part. I think when you specify atomic uninstall $NAME, the system container(container in ostree backend) will be uninstalled if and only if the container has the same name with the image right?

no, it will look at the container named NAME for the ostree backend.  It doesn't know from what image it is coming from.

If it doesn't, then it is a bug :-)

**Comment by peterbaouoft** [comment]
Oh, yea, now I think I understand. Thanks for the clarification. I was confused about `atomic uninstall --storage ostree $NAME` and mixed it up with `atomic uninstall $NAME`. 

**FTR**: When you specify the storage to be ostree, it will default to finding the image, which lead to the failure example I mentioned earlier. Hmm, I think we should not care too much when user specify the storage then. I will modify the PR based on your reply. Thanks :-).
