### ISSUE TITLE
atomic mount read-write mode broken in atomic-1.22.1 version

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomic#1222]
latest version: `atomic-1.22.1-1.gitd36c015.el7.centos.x86_64` 
Working version:  `atomic-1.20.1-9.git436cf5d.el7.centos.x86_64`

Functionality broken: `atomic mount -o rw $IMAGE $MOUNTPOINT`

Issue:
 - `atomic mount` will mount the image in read-only mode, even if `rw` option is provided.

Re-produce:
```
$  yum install atomic
$ docker pull registry.centos.org/centos/centos:latest
$ atomic mount -o rw registry.centos.org/centos/centos:latest /mnt
$ touch /mnt/foo
touch: cannot touch ‘/mnt/foo’: Read-only file system 
```

Expected behavior: 
With working version mentioned, mounted an image with `rw` option, the image will be mounted in read write mode.

**Comment by navidshaikh** [comment]
The older version of atomic will give the warning about not supported OverlayFS backend

```
# rpm -q atomic
atomic-1.20.1-9.git436cf5d.el7.centos.x86_64

# atomic mount -o rw registry.centos.org/centos/centos /mnt
The OverlayFS backend does not support writeable mounts.
```

while the latest version doesn't warn about not supported OverlayFS backend 
```
# rpm -q atomic
atomic-1.22.1-1.gitd36c015.el7.centos.x86_64
# atomic mount -o rw registry.centos.org/centos/centos /mnt
# echo $?
0
```

**Comment by rhatdan** [comment]
@baude @giuseppe PTAL

**Comment by giuseppe** [comment]
PR here: https://github.com/projectatomic/atomic/pull/1223

**Comment by navidshaikh** [comment]
@rhatdan : Since`overlay2` is recommended and default storage option, we had to use `devicemapper` option for writable writable mounts (for atomic scanners).  

What are recommendations on using `devicemapper` for production use cases?

Writable mounts could be a possible use case, are there plans for overlay2 to support writable mounts ?

**Comment by rhatdan** [comment]
@navidshaikh Why do you need writable mounts for scanning?  You should not be writing to the rootfs?

**Comment by rhatdan** [comment]
Yuck.

**Comment by giuseppe** [comment]
can you mount the container and then add a tmpfs on top of it with overlayfs?  That should solve the issue you have seen

**Comment by navidshaikh** [comment]
> and then add a tmpfs on top of it with overlayfs

@giuseppe : Can you please help clarify "add a tmpfs on top of it with overlayfs"? As in, how to add another tmpfs on a mounted container?

**Comment by giuseppe** [comment]
@navidshaikh yes exactly, or you can use a temporary directory as the upper layer, something like:

```
mount -t overlay overlay -o lowerdir=mounted-container,upperdir=/tmp/somewhere/up,workdir=/tmp/somewhere/wd mounted-writeable
```

**Comment by rhatdan** [comment]
Perhaps that is something we could automate in the command, although we would have to point out that changes will be lost when the container is umounted.
