### ISSUE TITLE
atomic pull fails with KeyError: 'Registries'

### ISSUE THREAD

**Issue by Zebirdman** [projectatomic/atomic#1232]
I have a small network of five virtual machines using Red Hat OS 7.4, atomic 1.20.1, Docker 17.06.2-ee-6 on four nodes with one node running Docker 17.12.1-ce for testing purposes.

My manager/server node is running a container image of Docker distribution (registry) which i have created TLS keys for and distributed to all nodes in the /etc/certs.d/redhat.repo:443 directory so standard docker push pull works fine.

After following the Red Hat documentation i was able to tag an image then sign and push it successfully 
_atomic push redhat.repo:443/app-1:1.0_

However when i try to do a atomic pull on my other nodes
_atomic pull redhat.repo:443/app-1:1.0_
i end up with the following debug output. This happens on nodes with both versions of Docker whether i try a pull using the public key to verify or just do an insecure pull (add registry redhat.repo:443 as insecureAcceptAnything).

My VM work environment is air gapped and i had to write this out by hand so hopefully there's no errors in there. Im fairly new to everything linux so please go easy if i have done something obviously silly, thankyou

Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='redhat.repo:443/app-1:1.0, profile=False, reg_type=None, src_creds=None, storage=None)
'Registries'
Traceback
  File "/bin/atomic", line 185, in <module>
      sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 54, in pull_image
      remote_image_obj = be.make_remote_image(self.args.image)
  File "/usr/lib/python2.7/site-packages/Atomic/backends/_docker.py", line 271, in make_remote_image
      img_obj.populate_remote_inspect_info()
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 157, in populate_remote_inspect_info
  File "/usr/lib/python2.7/site-packages/Atomic/objects/image.py", line 173, in remote_inspect
      tag=self.tag, digest=self.digest, orig_input=self.input_name)    # on a side note no opening bracket?
  File "/usr/lib/python2.7/site-packages/Atomic/discovery.py", line 16, in __init__
      self.registries = util.get_registries()
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 115, in get_registries
      search_regs = [x['Name'] for x in dconf['Registries']]
KeyError: 'Registries'

**Comment by rhatdan** [comment]
@baude Ideas?

**Comment by baude** [comment]
does "redhat.repo" resolve? like with ping? does it pull with straight docker correctly?

the more i look at the output, it looks like you might be missing or have a bad /etc/containers/registries.conf ?

**Comment by Zebirdman** [comment]
yes all hosts on my network can ping each other by hostname as i added these to the `/etc/hosts` and standard `docker push pull` all work fine.

like you said though i am missing the `/etc/containers/registries.conf` file, did not mention this file in the Red Hat docs i read here https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/signing_container_images.

My `/etc/atomic.conf` file is pointing the `registry_confdir` to `/etc/containers/registries.d` and inside here there is a yaml file for my registry that seems to be configured correctly. So im guessing i should create this `/etc/containers/registries.conf` file and put something in there that will be used to feed into that array key at some point?

**Comment by Zebirdman** [comment]
ok so the issue is a simple matter of package dependencies. I am testing out Docker but installed it by rpm not via yum.

This process meant that the atomic-registries package was not installed even when i installed the atomic package via yum to test out image signing. Long story short, messing about with Openshift on a new VM I installed everything via the provided Red Hat packages and the missing dependency was pretty obvious. 

Please close this issue, thankyou.
