### ISSUE TITLE
atomic mount fails consistently

### ISSUE THREAD

**Issue by ibotty** [projectatomic/atomic#124]
using atomic-1.1-1.git5f631c8.fc22.x86_64 but the changes since that revision seem insignificant re that issue. 

```
$ atomic mount doesn_t_matter /path
Traceback (most recent call last):
  File "/bin/atomic", line 306, in <module>
    sys.exit(args.func())
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 705, in mount
    self.args.live).mount(self.args.image, options)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 268, in mount
    driver_mount_fn(identifier, options)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 302, in _mount_devicemapper
    cid = self._identifier_as_cid(identifier)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 214, in _identifier_as_cid
    if (__cname_matches(c, identifier) or
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 209, in __cname_matches
    return any([n for n in container['Names']
TypeError: 'NoneType' object is not iterable
```

The code in question does not check for a (docker's) container to have `None` as `Names` key, which apparently `Dead` container have:

```
>>> [c['Status'] for c in cli.containers(all=True) if c['Names'] is None ]
[u'Dead']
```

The code in question should maybe just skip these containers, i.e. (maybe non-idiomatic python following)

```
diff --git a/Atomic/mount.py b/Atomic/mount.py
index cf0ff07..7f1446e 100644
--- a/Atomic/mount.py
+++ b/Atomic/mount.py
@@ -214,7 +214,7 @@ class DockerMount(Mount):
         container and return its uuid.
         """
         def __cname_matches(container, identifier):
-            return any([n for n in container['Names']
+            return any([n for n in (container['Names'] or [])
                         if matches(n, '/' + identifier)])
 
         # Determine if identifier is a container
```

**Comment by rhatdan** [comment]
@baude @willmtemple Does this make sense to you guys?

**Comment by ibotty** [comment]
Am I being unclear? Maybe I explained it confusingly.

**Comment by rhatdan** [comment]
@ibotty Not it is clear, I just want to confirm with @baude and @willmtemple that your fix is good before merging.  You should probably open a pull request.

**Comment by ibotty** [comment]
Already did: issue #126

**Comment by baude** [comment]
yes this makes sense I believe.  I havent tested the mount command on dead containers but I have had trouble coding to them in the past.

**Comment by ibotty** [comment]
Oh, the big problem is not matching dead containers, but not erroring out when encountering them. This code still won't match dead containers, because they have no tags (and one might argue that an empty list is the right value, not `None`, but that's a docker-py issue, I suppose).

**Comment by rhatdan** [comment]
Since https://github.com/projectatomic/atomic/pull/126 is merged closing.
