### ISSUE TITLE
atomic uninstall does not run what is in UNINSTALL label

### ISSUE THREAD

**Issue by hhorak** [projectatomic/atomic#128]
My intention is to install a container from image and then uninstall just that one container (without removing image itself).
```
#> atomic install -n myc1 --opt2='-e MYSQL_USER=myuser -e MYSQL_PASSWORD=mypass -e MYSQL_DATABASE=mydb' 60bfde38982e
#> atomic install -n myc1 60bfde38982e
```
First problem I have is that `-n` is not documented.

Second and more important is that using the above the command specified in `UNINSTALL` label is not run (in this context the systemd service file installed during `atomic install` is not removed).

Maybe I just don't understand how the `atomic uninstall` is intended to work, but I suspect the `return` at https://github.com/projectatomic/atomic/blob/master/Atomic/atomic.py#L482 is causing the issue.

**Comment by aveshagarwal** [comment]
I have seen this issue too and it worked when I rerun the command again.

**Comment by hhorak** [comment]
Reading it again, my example should have included `uninstall` on the second line:
```
#> atomic install -n myc1 ... 60bfde38982e
#> atomic uninstall -n myc1 60bfde38982e
```

**Comment by hhorak** [comment]
Full example available at https://github.com/openshift/mysql/pull/83.

**Comment by rhatdan** [comment]
Does this work correctly with the current atomic command?

**Comment by hhorak** [comment]
No, it is still the same. Either I use it wrong or it just still doesn't work. Looking at the code, the line https://github.com/projectatomic/atomic/blob/master/Atomic/atomic.py#L518 checks `self.name != self.image`, which is my case and then it is obvious it never get's to UNINSTALL label, since there is return on line 523.

**Comment by rhatdan** [comment]
Does https://github.com/projectatomic/atomic/pull/168 fix the problem?

**Comment by hhorak** [comment]
Almost, it runs the uninstall script, but then it tries to remove the image itself, which is weird:
```
#> atomic install -n myc1 --opt2='-e MYSQL_USER=myuser -e MYSQL_PASSWORD=mypass -e MYSQL_DATABASE=mydb' 5a21ccbafb95
docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR= -e CONFDIR= -e DATADIR= -e IMAGE=5a21ccbafb95 -e NAME=myc1 -e OPT1 -e OPT2 -e OPT3  5a21ccbafb95 /usr/share/container-layer/mysql/atomic/install.sh
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
c92fe6eebc85b776de7d944f19776ace55d8e8263e967bfcf6696cfdd6cfa45e

#> atomic uninstall -n myc1 5a21ccbafb95
docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR= -e CONFDIR= -e DATADIR= -e IMAGE=5a21ccbafb95 -e NAME=myc1 -e OPT1 -e OPT2 -e OPT3  5a21ccbafb95 /usr/share/container-layer/mysql/atomic/uninstall.sh
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
rm '/etc/systemd/system/multi-user.target.wants/myc1.service'
/usr/bin/docker rmi 5a21ccbafb95
Error response from daemon: Conflict, cannot delete 5a21ccbafb95 because the container 535f8c70e723 is using it, use -f to force
Error: failed to remove images: [5a21ccbafb95]
```

**Comment by rhatdan** [comment]
Oops that was a bug.  I had to fix the check.  Should only attempt to remove if name == image.  Fixed in latest push.

**Comment by hhorak** [comment]
Now it looks fine, thanks.

**Comment by rhatdan** [comment]
Merged change.
