### ISSUE TITLE
atomic stop errors out because opt* args are not there for stop

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic#137]
In the `cmd_env(self)` function the call to self.args.opt1 gives an error because stop doesn't have an `opt1` arg. 

```
[root@f22 foo]$ atomic  stop delloapache                                                                                                                                                                                                    
Traceback (most recent call last):
  File "/usr/bin/atomic", line 306, in <module>
    sys.exit(args.func())
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 401, in stop
    self.display(cmd)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 759, in display
    "/usr/bin/echo \"" + cmd + "\"", env=self.cmd_env, shell=True)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 472, in cmd_env
    if self.args.opt1:
AttributeError: 'Namespace' object has no attribute 'opt1'
```

**Comment by praiskup** [comment]
Shouldn't be the 'optX' be rather removed completely?  The major problem is
that the --optX has no defined semantics (user -- while running some atomic --
command, has no idea what are the effects of that --optX option).  Because we
can pass arbitrary environment variable down to 'docker' now, we could
probably use something like `DOCKER_CMD_OPTS` instead of
$OPT2.

**Comment by rhatdan** [comment]
Yes makes sense to me.

**Comment by rhatdan** [comment]
@bexelbie @baude @scollier @cgwalters WDYT?

Does removing of this break anything?  If a user used $OPT1 in atomic

They would just need to do.

OPT1="--debug" atomic install foobar

Rather then 

atomic install --opt1="--debug" foobar

**Comment by goern** [comment]
@sub-mod this question is also for you...

**Comment by rhatdan** [comment]
I think I can leave the commands in atomic, but just don't document them

**Comment by sub-mod** [comment]
I unfortunately need optX to be present in atomic and in atomicapp LABELs to continue supporting deployment of  nulecule apps via cockpit.

**Comment by rhatdan** [comment]
THe current patch will still support --opt1 but it is no longer documented.  Preferred method would be to execute

OPT1="--option" atomic run foobar

But 

atomic --opt1="--option" run foobar
