### ISSUE TITLE
atomic mount does not work when docker is not running

### ISSUE THREAD

**Issue by ibotty** [projectatomic/atomic#147]
Of course that's known (Atomic uses the docker api to mount after all).

Unfortunately that won't cover the use case of containers that need to be run before docker is up (networking containers, etc.)

I tried to shoehorn that into Atomic/mount.py, but it does not really belong there, being fundamentally different than the other way to mount.

So, what's the best way forward? Do you agree that use case is worth supporting?

**Comment by rhatdan** [comment]
We are working on splitting out the graphc/libgraphdriver into a separate package like runc/libcontainer.

The idea would be to be able to mount up an image outside of the docker daemon, and then have the docker daemon use the image when it comes up.  We will attempt to get this split into docker when we have a working demo.

The biggest problem is moving the locking of the grapdriver out of process memory into a the file system.

A side benefit of this might be to allow shared storage for graph drivers.

**Comment by rhatdan** [comment]
@nalind

**Comment by rhatdan** [comment]
Since we have system containers now I think we can close this issue
