### ISSUE TITLE
kube-ui for atomic?

### ISSUE THREAD

**Issue by v1k0d3n** [projectatomic/atomic#149]
are there any instructions for using kube-ui on atomic? it doesn't appear to be included in the distro, but i was wondering if there's any way it can be added or if there's any consideration for adding it?

**Comment by charliedrage** [comment]
I don't believe so. 

But there is http://www.projectatomic.io/docs/cockpit/ as well as a nulecule/atomicapp plugin that's been implemented http://stef.thewalter.net/cockpit-kubernetes-dashboard.html

**Comment by v1k0d3n** [comment]
ah, ok...i was wondering if cockpit was going to be a competing ui for kube-ui. it looks like it is (which i'm happy to hear). the project looks awesome! eager to try it out. is it working from a user-testing perspective yet?

**Comment by v1k0d3n** [comment]
closing ticket in order to use Cockpit with Kubernetes: https://github.com/cockpit-project/cockpit/tree/master/pkg/kubernetes
