### ISSUE TITLE
Please remove the self.gen_cmd() hack (aka -e IMAGE vs. -e IMAGE=IMAGE)

### ISSUE THREAD

**Issue by praiskup** [projectatomic/atomic#150]
I see its probably for backward compatibility, but how about to make this
compat-hack at least opt-in (or in the worst-case opt-out)?

I was really confused why DATADIR or OPT{1,2,3} variables are carried
through docker command by `INSTALL="docker run -e DATADIR -e OPT1..."` but
`INSTALL="docker run -e NAME ..."` has (usually) "no effect".

Implementation:
https://github.com/projectatomic/atomic/blob/d242bc65131d4306c2a9bf82c4d8072f6fe02bb9/Atomic/atomic.py#L551

**Comment by rhatdan** [comment]
The correct syntax would be to have

```
-e IMAGE=\${IMAGE}
```

Not sure why you would pass that into the container, though.

I have another pull request to remove DATADIR stuff.

-e DATADIR does not do anything, it is invalid syntax.

**Comment by praiskup** [comment]
> The correct syntax would be to have
>
> -e IMAGE=\${IMAGE}

As far as ${IMAGE} does not contain spaces and other "dangerous"
characters, yes ($IMAGE is (and will be) safe variable).  But with other
variables like ${OPT2} it is not correct and we should probably
use -e IMAGE=\"\${IMAGE)\" from within INSTALL.

> Not sure why you would pass that into the container, though.

@hhorak used that to allow privileged container to create container on
host, e.g.:
https://github.com/hhorak/postgresql/blob/860e063745e120f563cc5a8998aed74e055bdcd6/9.2/atomic-contrib/install.sh

> I have another pull request to remove DATADIR stuff.

Reference: projectatomic/atomic/pull/148

> -e DATADIR does not do anything, it is invalid syntax.

Hmm, I haven't found it docummented -- possibly documentation bug or
unintended behavior, but this syntax on my rhel atomic host is equivalent
to DATADIR=\${DATADIR} (iow define the variable if it is already available
in environment of docker process).

**Comment by rhatdan** [comment]
I don't believe IMAGE can container spaces for a container image.  So I think that is safe.

**Comment by praiskup** [comment]
You are right, $IMAGE sounds like safe variable, but its worse for $NAME:

  `atomic install -n "useful app"`

You are more safe to use `-e NAME` than `-e NAME=\${NAME}`.  Or, if the
`-e NAME` is really invalid, docs should rather document pattern like
`-e NAME=\"\${NAME}\" -e IAMGE=\"\${IMAGE}\"`.

**Comment by rhatdan** [comment]
docker run --privileged -ti --rm --name="This is a test" fedora echo hello
Error response from daemon: Invalid container name (This is a test), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

Well not supported on docker...

**Comment by praiskup** [comment]
I suppose also service name can't contain space too .. and there will be other
issues probably, but due to this atomic install might go through unexpected
code path..:

  ```
  bash-4.2# atomic install -n my\ app --opt2='...' ...
  docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host
    --pid=host -e HOST=/host -e LOGDIR=/var/log/postgresql 21 ...
  Unable to find image '21:latest' locally
  Trying to pull repository registry.access.redhat.com/21 ... not found
  Trying to pull repository docker.io/21 ... not found
  Error: image library/21:latest not found
  ```

Its not 100% obvious that shell expansion might happen too.

**Comment by rhatdan** [comment]
Most of this has been simplified, can we close this issue with current atomic.

**Comment by praiskup** [comment]
I would say yes, there are good tools to work  but I would rather have this documented:
  `-e IMAGE=\"\${IMAGE}\"`
not:
  `-e IMAGE=\${IMAGE}`
This escaping issue is common and known issue in shell programming,
I don't think we should suggest people to do this.  Even though $IMAGE is
safe, other environment variables (implemented in the meantime) might not be.

Is the `IMAGE=IMAGE` hack still needed, btw?

**Comment by rhatdan** [comment]
It was documented at one time, so removing it could potentially break other machines.

**Comment by praiskup** [comment]
Looks like the documentation has not been fixed, was it?  People might be
confused that they don't have to care about shell quotes..
