### ISSUE TITLE
Using systemd unit file for apps shouldn't be considered best practice

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/atomic#151]
After discussion with @sctweedie we agreed that [atomic install](https://github.com/projectatomic/atomic#atomic-install) example should be rewritten without suggesting to copy the systemd unit file to the host filesystem. 

Although this is ok for SPCs which should serve as atomic host extension, it shouldn't be used for applications (like databases) and using `docker run ... --restart=always` in `RUN` label should be recommended instead.

**Comment by hhorak** [comment]
There is one issue with this approach, that in case you for example misconfigure container and it exits early during initialization, then what you get with `--restart=always` is a forever restarting container. We can limit this by using something like `--restart=on-failure:5` which says try restart only 5 times, then give up.

**Comment by rhatdan** [comment]
I think we should have multiple examples.  Including a k8s example.

**Comment by rhatdan** [comment]
Where are the documents written describing best practices?

**Comment by hhorak** [comment]
@rhatdan I took the following file as the best practice guide: https://github.com/projectatomic/atomic/blob/master/README.md

**Comment by vpavlin** [comment]
There is a [Container Best Practices](https://github.com/projectatomic/container-best-practices/) project which should cover those, though it seems a bit frozen (Any comments, @scollier ?:)

**Comment by rhatdan** [comment]
Ok I guess we need to update this to show example of using k8s and docker for startin

**Comment by rhatdan** [comment]
Ok I guess we need to update this to show example of using k8s and docker for starting containers.

**Comment by rhatdan** [comment]
Does anyone have examples of these use cases that I could steal, or even better wanted to send me a pull request to update the examples.

**Comment by rhatdan** [comment]
Never received any other examples so I will close this issue.
