### ISSUE TITLE
Define the openscap-daemon image name

### ISSUE THREAD

**Issue by baude** [projectatomic/atomic#154]
With https://github.com/projectatomic/atomic/pull/152, if we don't find the dbus bus for the openscap-daemon, we exit with error.  The error should tell the user what image needs to be pulled from the redhat registry.  As of now, that is still being defined.  We may also additionally attempt to pull the image automatically should the 'scan' subcommand be pulled.

**Comment by rhatdan** [comment]
I don't think we should pull the service automatically.  We can define a default service and mention the container image, but I don't want to hard code the container image name into atomic command.

**Comment by rhatdan** [comment]
Can I close this issue now that your patch is merged.

**Comment by rhatdan** [comment]
@baude ????
