### ISSUE TITLE
Allow to set docker options in default INSTALL/RUN

### ISSUE THREAD

**Issue by hhorak** [projectatomic/atomic#157]
This issue will be discovered every time when docker arguments for running/creating container are not static.

For example mysql image expects to set some docker options by users (`-e MYSQL_USER=myuser`) and thus we can't set those in INSTALL/RUN labels. For more background see https://github.com/openshift/mysql/pull/92.

We want to allow users to specify these arguments as `atomic install <img> -e MYSQL_USER=myuser`, so, what we do in mysql case to enable atomic support are basically two things:
* take all arguments and use them as docker options, rather than CMD + args, which is default
* prepare data directory (this parses also the arguments to find whether `-u` is used, so we can set proper permissions for the data dir)

I think similar issues will have other images as well, so atomic command could support them better.

Some quick proposal from top of my head:
Additional arguments are separated by `--` to docker arguments and rest arguments:
```
atomic install <img> -e MYSQL_USER=myuser -u=1000 -- mysqld --help
```

Of course we can implement that in every image, but I think this could be the default behavior.

**Comment by rhatdan** [comment]
Why can't your install script handle this?  

```
label INSTALL=docker run \${IMAGE} /usr/bin/install.sh
```
```
atomic install <img> -e MYSQL_USER=myuser -u=1000 -- mysqld --help
```
Would run
```
docker run <img> /usr/bin/install.sh -e MYSQL_USER=myuser -u=1000 -- mysqld --help
```


I don't see this as something atomic needs to handle separately from the --opt1, --opt2 --opt3 support we currently have.

Your example of 

```
atomic install <img> -e MYSQL_USER=myuser -u=1000 -- mysqld --help
```
atomic install --opt1="-e MYSQL_USER=myuser -u=1000" <img> mysqld --help

Would do it now.

But this is really something for your install procedure or nulecule/atomicapp  not for the atomic command.

**Comment by hhorak** [comment]
Yes, that's for sure possible, but we might end up with every image doing it slightly different. What we've tried so far with images is to make them look similar and let users to use them the same way if possible.

If there was some support for that in the atomic itself, we also could remove INSTALL section for many images (unless we want to do something extra, as initializing DATADIR). Which would have one nice benefit that we can fix issues with basic running on one place, rather than in every image separately.

Anyway, it mostly depends on whether atomic should be general tool that allows you to do anything or it should do as much as possible for some sane default use cases (which it already does in case labels are not defined). But the example with `--opt1` looks quite sane.

**Comment by rhatdan** [comment]
Can I close this now that I am leaking the environment to the docker run command?

**Comment by hhorak** [comment]
For the case of MySQL image, we'll still need to set the arguments somehow. We can either let user to define variables before, or using `read -s MYSQL_PASSWORD` in the beginning of the INSTALL label. But if we want to support passing such input as arguments as well (so it is scriptable), we'll have to write more complicated `install.sh`, so I don't see much help here.

**Comment by hhorak** [comment]
Just talked to @praiskup and realized it is not that big difference from the ideal way (from my PoV)
```
atomic install -e MYSQL_USER=myuser <img>
```
and this way, that should work already now:
```
MYSQL_USER=myuser atomic install <img>
```
(while here install.sh just needs to pass all known variables in the form of `-e MYSQL_USER` to the `docker create` command)

The current implementation also doesn't allow to specify other options (like `-u 1000`), but this also can be done as follows:
```
CONTAINER_USER=1000 atomic install <img>
```
while install.sh would convert it into `docker create -u $CONTAINER_USER <img>`.

Anyway, I think we should be fine with the current implementation -- it is flexible enough and allows `atomic` to stay simple enough.

The only thing we risk is that every container will support different way of processing additional arguments -- one by setting variables, another by parsing additional variables after.. If any of the variants seems more correct from atomic authors' PoV, we should document it as best practice to help keep containers more similar.

**Comment by rhatdan** [comment]
.I still don't see why this is not good enough

atomic install <img> --user=1000

Then your install.sh would have a default user and if --user is specified override it.

**Comment by hhorak** [comment]
Because in worst case (but still real example) user passes two types of arguments to the image when running `atomic run ...`:

* arguments for the docker (-e, --user) that must be used before <img>
* CMD + args to run inside container (for case we want to run master/slave for example) that must be used after <cmd>

So install.sh would have to parse those arguments and pass them into appropriate place when calling `docker create`:
```
docker create ...-e ... --user ... <img> CMD args
```

As you say, it is possible, but makes the install.sh more complicated and every image will approach this problem differently, which is what I'd like to avoid.

**Comment by praiskup** [comment]
On Wednesday 23 of September 2015 05:37:44 Daniel J Walsh wrote:
> I still don't see why this is not good enough
> 
> atomic install <img> --user=1000
> 
> Then your install.sh would have a default user and if --user is
> specified override it.

This sounds unnecessarily complicated.. :(  The only thing I need to
accomplish by 'atomic install -u 1000 image' is

  `docker create -u 1000 -v /from:/to:Z image`

With your example `atomic install <img> --user=1000`, I need to prepare
`install.sh` that (a) implements option parsing and especially is (b) is
started in _privileged_ container because I need to re-execute
'/bin/docker'.

**Comment by rhatdan** [comment]
Does the 1000 have any relationship to the user running atomic install?  If yes then SUDO_UID is set. 

Not sure you could override with SUDO_UID=1000 atomic create foobar

It would be nice to be able to set a default and then allow user at command line to override it.

**Comment by praiskup** [comment]
@rhdan wrote:
> Does the 1000 have any relationship to the user running atomic install? If
> yes then SUDO_UID is set.  Number 1000 was just badly chosen example.

This all is inspired by longly discussed OpenShift's issue about arbitrary UID
of running process in container.

Typically, UID=26 (Dockerfile USER 26) is used for PostgreSQL container.  But
somebody might want to run the PostgreSQL server under arbitrarily UID which
is not related to SUDO_UID, and that is usually done by
`docker run -u ARB_UID ... postgresql-image`.

**Comment by rhatdan** [comment]
I am not sure of the best answer here.
I guess this is what we have now.

LABEL RUN docker run -u ${USER} --name \${NAME} \${IMAGE}

And user of the tool has to specify

USER=1000 atomic run postgresql

If the user just runs 
atomic run postgresql

The docker run command will fail.

**Comment by rhatdan** [comment]
How about 

LABEL RUN docker run -u \${USER-"1000"} --name \${NAME} \${IMAGE}

This says user $USER if it is set else use 1000

**Comment by praiskup** [comment]
Yep, the corrected example is something I wanted to post now.  But you should
still use double quotes around the variable, imo.

**Comment by rhatdan** [comment]
Now 

atomic run postgresql 

would work.  And 

USER=10001 atomic run postgresl

Would work

**Comment by rhatdan** [comment]
Closing since I believe this issue is resolved.
