### ISSUE TITLE
`atomic unmount path` not working as expected

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/atomic#186]
`atomic unmount path` complains that the mount point is not a docker container.  It removes one of the two mount entries and leaves what looks like the layered fs references in place.

Fedora 22
atomic-1.1-1.git5f631c8.fc22.x86_64

---

    bexelbie@bexelbie:~$ mkdir bex_mount
    bexelbie@bexelbie:~$ sudo atomic mount mysql bex_mount
    bexelbie@bexelbie:~$ mount | grep bex_mount
    /dev/mapper/docker-253:2-1451009-444fb76932aeb58f9f47946c1c380364353db3a000b9aea0322b19ae70812c08 on /home/bexelbie/bex_mount type xfs (ro,nosuid,nodev,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c4,c384",attr2,inode64,sunit=1024,swidth=1024,noquota)
    /dev/mapper/docker-253:2-1451009-444fb76932aeb58f9f47946c1c380364353db3a000b9aea0322b19ae70812c08 on /home/bexelbie/bex_mount type xfs (ro,nosuid,nodev,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c4,c384",attr2,inode64,sunit=1024,swidth=1024,noquota)
    bexelbie@bexelbie:~$ ls bex_mount
    bin   dev                         entrypoint.sh  home  lib64  mnt  proc  run   selinux  sys  usr
    boot  docker-entrypoint-initdb.d  etc            lib   media  opt  root  sbin  srv      tmp  var
    bexelbie@bexelbie:~$ sudo atomic unmount bex_mount
    Device mounted at bex_mount is not a docker container.
    bexelbie@bexelbie:~$ mount | grep bex_mount
    /dev/mapper/docker-253:2-1451009-444fb76932aeb58f9f47946c1c380364353db3a000b9aea0322b19ae70812c08 on /home/bexelbie/bex_mount type xfs (ro,nosuid,nodev,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c4,c384",attr2,inode64,sunit=1024,swidth=1024,noquota)
    bexelbie@bexelbie:~$ ls bex_mount/
    id  rootfs
    bexelbie@bexelbie:~$ sudo atomic unmount bex_mount
    Device mounted at bex_mount is not a docker container.
    bexelbie@bexelbie:~$ mount | grep bex_mount
    /dev/mapper/docker-253:2-1451009-444fb76932aeb58f9f47946c1c380364353db3a000b9aea0322b19ae70812c08 on /home/bexelbie/bex_mount type xfs (ro,nosuid,nodev,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c4,c384",attr2,inode64,sunit=1024,swidth=1024,noquota)
    bexelbie@bexelbie:~$ ls bex_mount/
    id  rootfs
    bexelbie@bexelbie:~$ sudo umount bex_mount/
    bexelbie@bexelbie:~$ mount | grep bex_mount
    bexelbie@bexelbie:~$ rmdir bex_mount/

**Comment by rhatdan** [comment]
Could you verify this against atomic-1.4?

If it exists there could  you open a bugzilla.

Lokesh could you update the atomic version in f22?

**Comment by baude** [comment]
I think the following will fix it.

@rhatdan Can you review the patch
@bexelbie i built you a scratch RPM with the patch, mind seeing if this fixes it? -> http://koji.fedoraproject.org/koji/taskinfo?taskID=11461993

```
diff --git a/Atomic/mount.py b/Atomic/mount.py
index f1c9d57..6cbd669 100644
--- a/Atomic/mount.py
+++ b/Atomic/mount.py
@@ -448,22 +448,16 @@ class DockerMount(Mount):
         """
         Devicemapper unmount backend.
         """
-        pool = self.client.info()['DriverStatus'][0][1]
-        dev = Mount.get_dev_at_mountpoint(self.mountpoint)
+	def _get_all_cids():
+	    return [x['Id'] for x in self.client.containers(all=True)]
 
-        dev_name = dev.replace('/dev/mapper/', '')
-        if not dev_name.startswith(pool.rsplit('-', 1)[0]):
+	dev = Mount.get_dev_at_mountpoint(self.mountpoint)
+	cid = dev.split("-")[-1]
+	dev_name = dev.replace('/dev/mapper/', '')
+        if cid not in _get_all_cids():
             raise MountError('Device mounted at {} is not a docker container.'
                              ''.format(self.mountpoint))
 
-        cid = dev_name.replace(pool.replace('pool', ''), '')
-        try:
-            self.client.inspect_container(cid)
-        except docker.errors.APIError:
-            raise MountError('Failed to associate device {0} mounted at {1} '
-                             'with any container.'.format(dev_name,
-                                                          self.mountpoint))
-
         Mount.unmount_path(self.mountpoint)
         cinfo = self.client.inspect_container(cid)
```

**Comment by bexelbie** [comment]
@baude  I got this:

$ sudo atomic mount stoic_ritchie foo
Could not mount docker container:
mount -o ro,nosuid,nodev,context="system_u:object_r:svirt_sandbox_file_t:s0:c36,c923" /dev/mapper/docker-253:2-1451009-ea2a9e004cdcb12f4c34efa567ec6d843ece0d41eb0b5e12cdc638b828001b60 foo
mount: wrong fs type, bad option, bad superblock on /dev/mapper/docker-253:2-1451009-ea2a9e004cdcb12f4c34efa567ec6d843ece0d41eb0b5e12cdc638b828001b60,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by jlebon** [comment]
It seems @chuanchang encountered the same issue on 7.1.6, and filed [RHBZ1273365](https://bugzilla.redhat.com/show_bug.cgi?id=1273365).

**Comment by baude** [comment]
different atomic code base, but could be the same problem

**Comment by bexelbie** [comment]
The fixed branch worked for me.

**Comment by rhatdan** [comment]
Is this in master or a pull request from @baude ?

**Comment by baude** [comment]
@rhatdan the branch he tested contained two different branches from me.  I have PRs for both now.  They are the https://github.com/projectatomic/atomic/pull/191 and https://github.com/projectatomic/atomic/pull/188

**Comment by baude** [comment]
@bexelbie @rhatdan  are we ok to close this?

**Comment by rhatdan** [comment]
Fine with me.

**Comment by bexelbie** [comment]
Yes.
