### ISSUE TITLE
atomic host: Add --print-current-version

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#200]
This would be useful for people doing e.g. Ansible scripting to ensure they have a new enough host version.

See https://github.com/cgwalters/ostree-scripts/blob/master/print-current-version

Alternatively we could speak to the new DBus API in the future.

**Comment by rhatdan** [comment]
You want 
atomic host version?

**Comment by rhatdan** [comment]
@cgwalters PTAL

**Comment by cgwalters** [comment]
SGTM.

**Comment by rhatdan** [comment]
@sallyom If we have not lost you yet, could you look at this one?

**Comment by sallyom** [comment]
sure

**Comment by cgwalters** [comment]
This all said really the better fix might be adding a DBus API to rpm-ostree and just having this call it.  The downside is atomic would hard require the newer rpm-ostree.

**Comment by rhatdan** [comment]
We can do this but we need to coordinate the releases.

**Comment by rhatdan** [comment]
@cgwalters Any movement on this.  Need to update trello card.

**Comment by rhatdan** [comment]
@cgwalters Is this something you still  want or can I close this issue?

**Comment by cgwalters** [comment]
We now have `atomic host status --json`.
