### ISSUE TITLE
Consider LGPLv2+

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#21]
Speaking for myself, I've been moving away from "GPLv2+" by default for two reasons:
 - It inhibits code motion to shared libraries
 - The Apache 2.0 license is very popular, and incompatible with the GPLv2, which leads to GPLv3, which leads to a mess.

Any objections to using LGPLv2+?

**Comment by rhatdan** [comment]
LGTM

**Comment by pombredanne** [comment]
I can see that three files have been left aside in the switch to LGPL: atomic, atomic.sh and mount.py https://github.com/projectatomic/atomic/search?utf8=%E2%9C%93&q=%22GNU+GENERAL%22&type= .... Is this to be expected or just an oversight?
