### ISSUE TITLE
Documentation should clarify if atomic verify uses remote or local data

### ISSUE THREAD

**Issue by riekrh** [projectatomic/atomic#216]
https://github.com/projectatomic/atomic/blob/master/docs/atomic-verify.1.md should clarify whether only host-local information or remote registry information is used.

**Comment by rhatdan** [comment]
@baude Could you work on improving the man page and document with an example based on your current code?

**Comment by baude** [comment]
yup!

**Comment by baude** [comment]
Merged with https://github.com/projectatomic/atomic/commit/ac2f835bca574abeaa602dd35920722634b99644
