### ISSUE TITLE
Add 'atomic stop' command to stop an installed, running system container

### ISSUE THREAD

**Issue by markllama** [projectatomic/atomic#22]
Please add a "stop" operation to compliment 'atomic run'.  This command should issue the appropriate docker (or other) command to stop a system container that is running.

This will probably involve adding a check for a corresponding docker image LABEL directive: LABEL STOP='....'

The lifetime of a system container would then be:

atomic install
atomic run
(atomic update|stop ...)
atomic uninstall

**Comment by rhatdan** [comment]
I just checked in a new version of atomic with atomic stop.  Please check it out and see if it matches your needs.
