### ISSUE TITLE
Keyboard layout on Fedora Atomic virtual machine

### ISSUE THREAD

**Issue by Smana** [projectatomic/atomic#224]
Hello,

I don't know if it's the right place, so please let me know if i should ask somewhere else.
I'm working on a project wich installs kubernetes and deploy apps with Ansible. : https://github.com/ansibl8s
I would like to support Fedora Atomic (which is great and comes with all the required tools out of the box) so i'm currently doing some tests.
I've installed the Fedora Atomic image and chose the keyboard layout with the install wizard.
Unfortunately after the reboot, the French layout chosen doesn't seem to be supported.
I've this kind of error : 
```
-bash: warning: setlocale: LC_CTYPE: cannot change locale (fr_FR.UTF-8): No such file or directory
```
How can i install locales and change the keyboard layout please ?

Thank you,

**Comment by rhatdan** [comment]
For questions like this we usually suggest you install an SPC container which you could use as the admin shell.  This is what we do with the RHEL tools container.

http://developerblog.redhat.com/2014/11/06/introducing-a-super-privileged-container-concept/

Then you could install the French lanquage as well as locale info into this SPC and use that when you log onto the Atomic host.

**Comment by Smana** [comment]
Ok thank you, i'll do that :)

**Comment by miabbott** [comment]
@Smana See this issue filed against RHEL Atomic Host - https://bugzilla.redhat.com/show_bug.cgi?id=1186757
