### ISSUE TITLE
Atomic scan json -- mess on output

### ISSUE THREAD

**Issue by ybznek** [projectatomic/atomic#225]
When you want to get JSON output e.g. ``` atomic scan TEST_RHEL7 --json ```, 
you will get "Scanning..." before JSON data, so you cannot parse it easily.

Atomic should not prepend "Scanning..." before JSON. 

```
$ sudo atomic scan DOCKER_TEST_RHEL7 --json 2> /dev/null

Scanning...

{
    "allcontainers": false,
...
```

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/227 fixes this issue.
