### ISSUE TITLE
Add "atomic status" command to indicate the installation/configuration/runtime status of a system container.

### ISSUE THREAD

**Issue by markllama** [projectatomic/atomic#23]
Add an informational command to 'atomic' so that a user can determine the state of a system container.

atomic install
atomic run
atomic status [--quiet] [-output (none|text|json|yaml...)]

Status would return text or structured data via STDOUT which would indicate if a system container is correctly installed and running.

a shell return code of 0 would indicate that the container is running and has no status errors.
a non-zero return code would indicate that the container is not running or has some error status or both.

return code 0: running
return code 1: not running
return code N: >1 user defined

the --output .... option would indicate how to format the status output

text: format the output as human readable text
json: format the output as JSON encoded structured data
yaml: format the output as YAML encoded structured data.

The "status" command may require a new default behavior as well as a new Dockerfile LABEL directive:

LABEL STATUS="..."

The script provided in the STATUS label would be executed in response to the 'atomic status' command and the output and return code would be passed back to the caller.

**Comment by rhatdan** [comment]
I guess we could have atomic status default to return if a container is running, container exists, image exists.  

Do we need a status command to say whether or not a container is installed?  Or is the fact the container exists enough to tell you?

**Comment by markllama** [comment]
Hrrm.  Now I have to think about it :-)
Perhaps what I want is this:

atomic status <name>
PRESENT (the image has been pulled)
INSTALLED (install has been executed)
RUNNING (container exists and process is running)

Yeah, I may have gone a bit overboard with the output.

**Comment by rhatdan** [comment]
I am closing old issues to clean stuff up.  @markllama if you want to comment further I will reopen.
