### ISSUE TITLE
atomic install using default registries fails to execute after pull completes

### ISSUE THREAD

**Issue by markllama** [projectatomic/atomic#25]
When using the __atomic__ command to download and install a privileged service container
And the image name is not fully qualified
Atomic/Docker executes the _docker pull_ correctly, but then when attempting to run, fails to use the fully qualified image name (or fails to look up the possible matches for an unqualified name)

    bash-4.2# atomic install mlamouri/rhel7-ipa-client
    Pulling repository registry.access.redhat.com/mlamouri/rhel7-ipa-client
    Pulling repository docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client
    7d348a345a5f: Download complete 
    bef54b8f8a2f: Download complete 
    ...
    2ad47aa4dc10: Download complete 
    Status: Downloaded newer image for docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client:latest
    Traceback (most recent call last):
      File "/usr/bin/atomic", line 473, in <module>
        sys.exit(args.func())
      File "/usr/bin/atomic", line 338, in install
        self.inspect = self.d.inspect_image(self.image)
      File "/usr/lib/python2.7/site-packages/docker/client.py", line 709, in inspect_image
        True
      File "/usr/lib/python2.7/site-packages/docker/client.py", line 98, in _result
        self._raise_for_status(response)
      File "/usr/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    docker.errors.APIError: 404 Client Error: Not Found ("No such image: mlamouri/rhel7-ipa-client")

**Comment by rhatdan** [comment]
This might be a bug in the new registry handling.  

If you do a docker run -ti mlamouri/rhel7-ipa-client /bin/sh

Does it work?

**Comment by markllama** [comment]
__docker pull__ appears to use the registry list when a non-fully-qualified image ID is provided.
Others do not.

* docker pull - works
* docker run - pull works, run indicates no match 
* docker rmi - indicates no match

See examples below.

docker pull mlamouri/rhel7-ipa-client
Pulling repository registry.access.redhat.com/mlamouri/rhel7-ipa-client
Pulling repository docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client
7d348a345a5f: Download complete 
bef54b8f8a2f: Download complete 
...
0f4848afd108: Download complete 
66f86b8c458e: Download complete 
2ad47aa4dc10: Download complete 
Status: Downloaded newer image for docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client:latest

docker rmi  docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client

docker run mlamouri/rhel7-ipa-client
Unable to find image 'mlamouri/rhel7-ipa-client:latest' locally
Pulling repository registry.access.redhat.com/mlamouri/rhel7-ipa-client
Pulling repository docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client
7d348a345a5f: Download complete 
bef54b8f8a2f: Download complete 
42f92ea1e349: Download complete
...
0f4848afd108: Download complete 
66f86b8c458e: Download complete 
2ad47aa4dc10: Download complete 
Status: Downloaded newer image for docker-registry.usersys.redhat.com/mlamouri/rhel7-ipa-client:latest
FATA[0037] Error response from daemon: No such image: mlamouri/rhel7-ipa-client (tag: latest)

docker rmi mlamouri/rhel7-ipa-client
Error response from daemon: No such image: mlamouri/rhel7-ipa-client
FATA[0000] Error: failed to remove one or more images

**Comment by rhatdan** [comment]
What version of docker are you using?

**Comment by markllama** [comment]
-bash-4.2# docker version
Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.3.1
Git commit (client): d26b358/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.3.1
Git commit (server): d26b358/1.4.1

**Comment by rhatdan** [comment]
Can you try this with the docker-1.5 version.  docker-1.5.0-12.el7

**Comment by markllama** [comment]
Can you point me at an existing atomic-standard image which has this installed? (I'm working entirely from self-builds so I can experiment with different package sets.  This behavior is on the unmodified, but possibly old atomic-standard)

I'm also rebuilding my atomic-standard from the latest tree to see if it's in there.

**Comment by rhatdan** [comment]
Probably better to ask Collin.  There is a lot of work/patches around registry handling.

**Comment by markllama** [comment]
After updating the Atomic image to contain docker-1.5 all four atomic commands are able to run using unqualified image IDs:

* atomic install
* atomic run
* atomic stop
* atomic uninstall

Closing
