### ISSUE TITLE
atomic install/run

### ISSUE THREAD

**Issue by roldancer** [projectatomic/atomic#31]
Hi All,
    I would like to undestand when I should use "atomic run" intead of "docker run" ? 

It looks like atomic install/run command should be used for privileged container, shouldn't it ?

Many thanks.

**Comment by rhatdan** [comment]
atomic install is almost always going to be a Super Privileged Container.  Atomic run is just a helper app to allow a developer to add instructions to the docker image on how to run.  You can always to the same thing with a docker command, but it is often easier to use atomic run.

I plan on writing a blog on the atomic command this week to explain our thinking.

**Comment by roldancer** [comment]
@rhatdan Many thanks.

I have an issue when I push to my internal registry using Atomic Host, what should be the right github repository to report the issue  ?

**Comment by rhatdan** [comment]
If this is on RHEL, you should open a bugzilla.
