### ISSUE TITLE
Atomic mount of running container not mount running container

### ISSUE THREAD

**Issue by ybznek** [projectatomic/atomic#310]
When I do atomic mount container, it will made "snapshot" of container which is provided to mountpoint. But when I change something in container, I don't see change in my mountpoint.

Reproduce:

1) Have running container
```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
5e705a15ef52        fedora:22           "/bin/bash"         2 minutes ago       Up 2 minutes                            drunk_franklin
```
2) Create test file in container
```
[root@5e705a15ef52 tmp]# echo "" > /tmp/myTestFile1
```
3) Mount container
```
$ sudo atomic mount 5e705a15ef52 /tmp/m1
```
4) See existing test file from host
```
// /tmp/m1/tmp/myTestFile1 exists
```

5) Now I have mounted container and will create new file in running container
```
[root@5e705a15ef52 tmp]# echo "" > /tmp/myTestFile2
```

6) **I don't see it** in mounted directory
```
// /tmp/m1/tmp/myTestFile2 DOESN'T exist
```

I am expecting to see myTestFile2 in directory from host, too.

Workaround:
$ sudo docker inspect 5e705a15ef52 | grep -i pid
        "Pid": 8447,

$ cd /proc/8447/root/tmp/
I have here live FS from container

**Comment by rhatdan** [comment]
We don't want you to make changes to the container.  
We do not want scans of running container images, and their is no way to actually see the running container without entering the container, which would be potentially dangerous.  I am fine with just scanning the container image as rest.  Do not care for  you looking at the processes running inside of the container.  Basically handle container images and standard images the same way.  The scanner tool will just look at the files on disk and determine if their is something to worry abour.  
this is the model we have done for Black Duck also.
