### ISSUE TITLE
Does it make sense to have Commissaire Functionality Added to the Atomic command?

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/atomic#329]
We are currently looking to find the proper place for [Commissaire/Atomic Multi-Host Manager](https://github.com/projectatomic/commissaire)'s CLI to live. Two options that came up recently were:

- Add functionality to the atomic command
- Add a pass through from the atomic command to a Commissaire specific command (similar to https://github.com/projectatomic/atomic/blob/master/atomic#L142)

Personally, I'm a little more interested in the second of the two as it would allow users to use it directly. The additional functionality added by Commissaire would be things such as upgrades, restarts, grouping of hosts (currently called clusters but the name may change since the word is overloaded), etc..

Thoughts?

/cc @rhatdan @devop-mmcgrath @cgwalters @mbarnes

**Comment by ashcrow** [comment]
Spike Doc: https://github.com/projectatomic/commissaire/wiki/SPIKE:-Find-the-best-location-for-the-CLI

**Comment by jlebon** [comment]
I would vote for option two as well (or leaving it as standalone), just to keep the `atomic` codebase lean.

I guess it depends on other factors as well, e.g. could it happen that `commctl` gets rewritten in a different language? I remember mentions of keeping that door open at the beginning.

Also, are there situations where we would have to support nodes which might not have `atomic` installed? If it only requires kubernetes and etcd to work, that might be a nice property to keep.

**Comment by rhatdan** [comment]
Yes I think Option 2 also.

**Comment by mbarnes** [comment]
On 03/28/2016 11:41 AM, Stephen Milner wrote:
> Personally, I'm a little more interested in the second of the two as it
> would allow users to use it directly. The additional functionality added
> by Commissaire would be things such as upgrades, restarts, grouping of
> hosts (currently called clusters but the name may change since the word
> is overloaded), etc..
>
> Thoughts?

Commissaire's CLI tool is just a small amount of Python code [1].  It's 
just wrapping a REST API.  Adding a 1:1 command passthrough to atomic 
like we do for rpm-ostree would be, I think, almost as much code as the 
tool itself.

What if we instead provide a Python module with an API that takes and 
fleshes out an argparse.ArgumentParser in a way that atomic expects?

atomic would just need to import the module and hand it a new subparser.

That would avoid potentially maintaining command syntax in two places, 
and the standalone Commissaire tool (if we decide to keep it) would be 
trivial.

Matthew Barnes


[1] 
https://github.com/projectatomic/commissaire/blob/master/src/commissaire/client_script.py

**Comment by ashcrow** [comment]
@mbarnes interesting idea. I like it. IMO it's a different underlying implementation idea of Option 2. Instead of saying 'if binary is available then add this parser in atomic' it becomes 'if commctl library is available then import and append its parser', correct?

**Comment by ashcrow** [comment]
@jlebon it's possible. At this point I don't think it's probable. The original two languages we were looking at were Go and Python. At the start 3/3 of the folks working on commissaire knew Python while only 1/3 knew Go.

**Comment by mbarnes** [comment]
@ashcrow  Yeah, basically.  Something roughly like:
```
try:
    import commissaire.cli
    clusterp = subparser.add_parser("cluster", ...)
    cluster_subparser = clusterp.add_subparsers(help=_("cluster commands"))
    commissaire.cli.add_parsers(cluster_subparser)
except ImportError:
    pass
```

**Comment by ashcrow** [comment]
@mbarnes I updated Option 2 with the two possible implementation details.

**Comment by ashcrow** [comment]
It sounds like we are all in agreement that Option 2 makes the most sense. Unless I get a dissenting post we will move forward with that. Thanks everyone!

**Comment by ashcrow** [comment]
Closing this issue. Thanks!
