### ISSUE TITLE
atomic run - not predictable format of output

### ISSUE THREAD

**Issue by ybznek** [projectatomic/atomic#338]
Hi,

I was using output of **atomic run** to get container id of started container, but it stopped to work.

*Expectation:*
- Container ID is last line of output / or
- in stdout should be only container ID, especially with --quiet

*Reality:*
- Container ID is somewhere in output
- stdout is full of some info messages what should be IMHO in stderr

In my opinion, it is bad that output isn't currently machine readable. Redirection of messages to stderr could be very helpful.

**Example 1: ID is last line of output**
```
$ sudo atomic run docker.io/openscap/openscap-daemon-f23  2> /dev/null

docker run -dt --privileged --pid=host -v /etc/oscapd:/etc/oscapd -v /proc/:/hostproc/ -v /sys/fs/cgroup:/sys/fs/cgroup -v /var/log:/var/log -v /run:/run -v /var/lib/docker/devicemapper/metadata/:/var/lib/docker/devicemapper/metadata/ -v /dev/:/dev/ -v /var/tmp/image-scanner:/var/tmp/image-scanner --env container=docker --net=host --cap-add=SYS_ADMIN --ipc=host docker.io/openscap/openscap-daemon-f23

This container uses privileged security switches:

INFO: --cap-add 
 ...
6ef654872b11ac5e1bafcf9ec2122a539d2e4371b826a956cfc9de6c49ea2329

```

**Example 2: ID is last line of output**
```
$ sudo atomic run -q docker.io/openscap/openscap-daemon-f23  2> /dev/null**

docker run -dt --privileged --pid=host -v /etc/oscapd:/etc/oscapd -v /proc/:/hostproc/ -v /sys/fs/cgroup:/sys/fs/cgroup -v /var/log:/var/log -v /run:/run -v /var/lib/docker/devicemapper/metadata/:/var/lib/docker/devicemapper/metadata/ -v /dev/:/dev/ -v /var/tmp/image-scanner:/var/tmp/image-scanner --env container=docker --net=host --cap-add=SYS_ADMIN --ipc=host docker.io/openscap/openscap-daemon-f23
2c597d73715160459ddd867572f3e53a588852fee5f8f45836c22d88a4cb3907

```

**Example 3: ID is not last line of output**
```
$ result=$(sudo atomic run -q docker.io/openscap/openscap-daemon-f23  2> /dev/null)
$ echo "$result"

a5cecf078c66224db54f875fa540432fffe71722f050171004baf742f1f3b263
docker run -dt --privileged --pid=host -v /etc/oscapd:/etc/oscapd -v /proc/:/hostproc/ -v /sys/fs/cgroup:/sys/fs/cgroup -v /var/log:/var/log -v /run:/run -v /var/lib/docker/devicemapper/metadata/:/var/lib/docker/devicemapper/metadata/ -v /dev/:/dev/ -v /var/tmp/image-scanner:/var/tmp/image-scanner --env container=docker --net=host --cap-add=SYS_ADMIN --ipc=host docker.io/openscap/openscap-daemon-f23
```

$ rpm -q atomic
atomic-1.9-4.gitff44c6a.el7.x86_64

**Comment by rhatdan** [comment]
The first line of output is just the command that the atomic run command is going to execute.  It is read from the LABEL RUN command imbeded in the Docker image.  It is not intended to indicate the UUID of the container, from a docker point of view.

atomic run could be an interactive shell.

**Comment by ybznek** [comment]
@rhatdan I understood that it is the label, but I would expect that order of lines will be always same - you can see example 2 vs example 3.

Did I understand well, that the output is for human and I should not parse (get container id from) it?

**Comment by rhatdan** [comment]
Yes we did not have the intention to show the Container ID, event though in certain situations we will show the information from the underlying tool like docker outputing the container uuid.

Atomic run is actually defined to work differently even from one run to the next.  It works on the concept of a PET Container.  In that it will create a container on the first run if the container does not exist.  If the container is running it will exec into it, if the container is stopped it will start and attach to it.

In only one case do we create a new container.  We always name the container, by default the container is named after the image.  You can override this behaviour by using the --name option.
