### ISSUE TITLE
Namespace OSTree Not Found

### ISSUE THREAD

**Issue by 14rcole** [projectatomic/atomic#357]
When I run `make all` I get an error stating

> /usr/bin/python setup.py build
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import Atomic as _Atomic
  File "/home/14rcole/Development/Docker/Atomic/atomic/Atomic/__init__.py", line 3, in <module>
    from .atomic import Atomic
  File "/home/14rcole/Development/Docker/Atomic/atomic/Atomic/atomic.py", line 17, in <module>
    gi.require_version('OSTree', '1.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace OSTree not available
Makefile:21: recipe for target 'python-build' failed
make: *** [python-build] Error 1

This seems to be an issue, but if I'm just forgetting to import something before running `make all` please let me know.  I'm running Fedora 23 if that helps with the issue.  Thanks!

**Comment by baude** [comment]
@14rcole i think you just need to dnf install libgsystem ostree

**Comment by 14rcole** [comment]
That worked, thannks!

**Comment by rhatdan** [comment]
We need to make sure that @lsm5 knows about this when we move to the next version of atomic.

**Comment by lsm5** [comment]
sure thing!

**Comment by cgwalters** [comment]
"continuous delivery" as implemented by https://ci.centos.org/job/atomic-rdgo-centos7/ implies continuous packaging.  See http://pkgs.fedoraproject.org/cgit/rpms/atomic.git/commit/?id=37863d55171f671b2f33ebe7a830dd5d76dad355

**Comment by rhatdan** [comment]
Nice
