### ISSUE TITLE
Permission denied to modify a volume directory

### ISSUE THREAD

**Issue by roberto-gomez** [projectatomic/atomic#36]
Hello.

I am trying to run a PostgreSQL container. The image have a volume in /var/lib/postgresql/data.

The command to run the container is : docker run -d postgres

The log: "chown: changing ownership of `/var/lib/postgresql/data': Permission denied"

I see that every operation over the volume directory is denied

The only way I have get to work is with the --privileged parameter in docker run command.

Perhaps SELinux is bloking the access?

**Comment by shaded-enmity** [comment]
Yes, you'll need to label the volume mount with `docker_var_lib_t`:

```bash
chcon -t docker_var_lib_t /var/lib/postgresql/data
```

See [Docker and SELinux - Project Atomic](http://www.projectatomic.io/docs/docker-and-selinux/)

**Comment by roldancer** [comment]
It works for me executing the following commands:

semanage fcontext -a -t svirt_home_t '/var/lib/postgresql/data(/.*)?'
restorecon -Rv /var/lib/postgresql/data

Bye.

**Comment by rhatdan** [comment]
The current docker with the -v source:dest:Z should fix this problem.
