### ISSUE TITLE
Problem when using VOLUMEN with SELINUX enabled

### ISSUE THREAD

**Issue by roldancer** [projectatomic/atomic#37]
Hi All,
    When your image uses VOLUMEN XXX and SELinux is enabled, there are some permission problems, for instance, if you use the following Dockerfile in RHEL 7.1 Atomic GA

FROM registry.access.redhat.com/rhel
MAINTAINER roberto.gomez@ext.produban.com
VOLUME /tmp/test
CMD [ "/usr/bin/bash" ]

docker run -ti -rm image_name 

[root@32e2fa9abc8a tmp]# cd test/
[root@32e2fa9abc8a test]# touch uno
touch: cannot touch 'uno': Permission denied

What we see ...

1) Every VOLUMEN directory is created in /var/lib/docker/vfs/dir by the docker daemon.

2) The VOLUMEN directory is created with label docker_var_lib_t
drwxr-xr-x. root    root system_u:object_r:docker_var_lib_t:s0 ee4be774547890ff718f319ba1438fe2b8eda33680ce91518d5ce37bb5f2bee0

2) If you change the VOLUMEN label to "svirt_home_t", the command:
 "touch uno" Works OK, so at this point we have several questions ...

1) What are we doing wrong with VOLUMEN ?

2) The directories created in /var/lib/docker/vfs/dir should be label with "svirt_home_t", shouldn't be?

3) This permission problem when working with volumen is a bug or special security feature?

Many thanks.

**Comment by rhatdan** [comment]
What version of docker are you seeing this with?

rpm -q docker

**Comment by roldancer** [comment]
-bash-4.2# rpm -q docker
docker-1.4.1-37.el7.x86_64

-bash-4.2# atomic host status

  TIMESTAMP (UTC)         VERSION   ID             OSNAME               REFSPEC                                                 
* 2015-02-19 20:26:26     7.1.0     5799825b36     rhel-atomic-host     rhel-atomic-host:rhel-atomic-host/7/x86_64/standard     


-bash-4.2# docker version

Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.3.1
Git commit (client): d26b358/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.3.1
Git commit (server): d26b358/1.4.1

-bash-4.2# docker info

Containers: 7
Images: 154
Storage Driver: devicemapper
 Pool Name: rah_vmlbcatoml01-docker--pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: <unknown>
 Data file: 
 Metadata file: 
 Data Space Used: 6.207 GB
 Data Space Total: 25.94 GB
 Metadata Space Used: 8.667 MB
 Metadata Space Total: 33.55 MB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Atomic Host 7.1
CPUs: 2
Total Memory: 1.797 GiB
Name: vmlbcatoml01.lvtc.gsnet.corp
ID: RHZI:DYCI:3ZUO:EAWE:62SV:VAJJ:A46D:O3NM:T73V:CPQF:MSSZ:LPBF

**Comment by rhatdan** [comment]
There should be a new version of docker-1.5 available either via yum or atomic host update, which should fix this issue.

**Comment by roldancer** [comment]
Hi @rhatdan , thanks for your response, we will try it soon.

Thanks.

**Comment by roldancer** [comment]
upgrading atomic host problem was fixed.
