### ISSUE TITLE
Support bind mounts (and other docker options)

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#39]
We should support e.g. `atomic run -v /var/local:/var/local rhel7/rhel-tools` so that people can easily transfer data.

Two options I see:

 - Explicit support for a subset of `docker run` options
 - Add `--docker-opt=-v  /var/local:/var/local rhel7/rhel-tools` or so (ugly but avoids us having to know about all options)

And...does this override or extend docker options?  (It seems like we'd have to know which options are singletons versus overridable...)

I'm leaning towards implementing `-v` specifically and adding `--docker-opt` as a generic escape hatch which would just append.

**Comment by rhatdan** [comment]
Yes I think this sounds good.  I know that Mark L Wanted to be able to extend the atomic run command also.

**Comment by cgwalters** [comment]
I tried in https://github.com/projectatomic/atomic/pull/40 but it needs work.

**Comment by rhatdan** [comment]
One Possibility would be to add Keywords to you label command which could be overwritten.

LABEL INSTALL="docker run -ti -v /:/HOST OPTIONS fedora /usr/bin/install.sh COMMANDOPTIONS"

Then we could allow developers to specify locations where OPTIONS could be added.  COMMAND OPTIONS, might just add options to the end of the selected command.

atomic install --options="-v /lib/modules:/lib/modules"

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/65 should solve this problem.
