### ISSUE TITLE
atomic install --system errors on fedora 24

### ISSUE THREAD

**Issue by aveshagarwal** [projectatomic/atomic#397]
I have a locally built flannel image on fedora 24. Installing the image with system flag errors:

atomic install --system flannel 
Cannot find a configured OSTree rep

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
Fedora has no OSTree repo, so one must be created manually:

```bash
# mkdir -p /ostree/repo && ostree --repo=/ostree/repo init --mode=bare
```

In alternative, it is possible to set a different location for it, and this must be reflected into the /etcd/atomic.conf file, uncommenting this line and setting the proper value:

```yaml
# ostree_repository: /ostree/repo
```

**Comment by rhatdan** [comment]
We should have the atomic tool do this automatically if the directory does not exist.  Have a default in the config and execute mkdir -p /ostree/repo && ostree --repo=/ostree/repo init --mode=bare from atomic.
