### ISSUE TITLE
Fix systemd unit for upcoming runc v1

### ISSUE THREAD

**Issue by runcom** [projectatomic/atomic#419]
New runc v1 (starting with rc1 also) has a new way of running runc with systemd, more info https://github.com/opencontainers/runc/issues/903

we should update atomic to use that

**Comment by papey** [comment]
To be more precise, it's a new workflow, more info : https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc1

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by mrunalp** [comment]
Refer to https://github.com/opencontainers/runc/pull/905 for updated Readme. We can use run instead of create start.

**Comment by rhatdan** [comment]
@mrunalp can you implement this change?  Should this be on the atomic command?  Or should we do this in docker?

**Comment by mrunalp** [comment]
Yeah, I'll make the change in atomic. We don't need changes in docker yet.

**Comment by giuseppe** [comment]
for system containers it will be enough, I think, to change the default configuration file we generate when an image has not a specified systemd unit file.  For the images, we will need to provide an updated configuration file:

https://github.com/giuseppe/atomic-oci-containers/pull/1

**Comment by mrunalp** [comment]
That PR looks good

**Comment by giuseppe** [comment]
This commit in atomic should fix this issue:

https://github.com/projectatomic/atomic/commit/cfb8e98c6d727aefe99c08007226880836a4b4e2

**Comment by rhatdan** [comment]
Should we close this issue?

**Comment by giuseppe** [comment]
@yuqi-zhang has done some testing with runc 1.0.  I would like to wait for his comments first

**Comment by yuqi-zhang** [comment]
Everything looks good to me. Only thing is some of the images used for the unit tests (e.g. atomic-test-system) should be updated to handle runc 1.0 properly.

**Comment by yuqi-zhang** [comment]
Tests are now fixed, everything looks good. Feel free to close.
