### ISSUE TITLE
The problem with labels

### ISSUE THREAD

**Issue by larsks** [projectatomic/atomic#43]
I think that treating container labels -- at least as implemented in
Docker -- as being similar to RPM header info is going to bring us
trouble and confusion.

Docker images are layered, while RPMs are not.  Docker images inherit
labels from parent images, which is going to lead to a variety of
problems largely concerning the accuracy of "provenance" information.
If one produces an image fedora/atomic-tools with:

    LABEL Name=fedora-tools-docker
    LABEL Vendor=Fedora Project, Inc.

And then I produce a new image from that with:

    FROM fedora/atomic-tools

My new image will have the same labels, even if it does something
completely different.  For someone not completely clued in to *our*
use of labels, this is going to result in the accumulation of crap
over time.

Having a "Name" label that is distinct from the name of the image is
also going to be a source of confusion.  With this and the preceding
facts about label inheritance, I can have an image named
"larsks/diagnostics" that will return something like
"fedora-tools-docker-21.1-9" in response to "atomic version".

Being able to mark labels as "private" such that they would not be
inherited by subsequent images would mitigate many of these issues,
but that (a) requires core docker changes and (b) probably involves
substantial complications to what is currently a relatively simple
feature.

I'm also not sure that operational labels like "RUN" can be
sufficiently generic to be useful outside of the "atomic" command line
itself.  Commands that involve volume mounts or access to the host
filesystem must necessarily make assumptions about the distribution in
place on the host.  That's fine if we're producing Fedora images for
use on Fedora platforms (or more broadly X images for use on X
platforms), but doesn't really lend itself to any sort of standard.
For these I think it makes far more sense to adopt the upstream
suggestion of using namespace-prefixed labels (e.g.,
io.projectatomic.atomic.run, io.projectatomic.atomic.install, etc).

**Comment by cgwalters** [comment]
I agree with all of this.  I would just make a slight distinction between `RUN` and `INSTALL`.  Theoretically the `RUN` command could be more host-independent than `INSTALL`.  But yeah...it would make sense to prefix all of them.

**Comment by rhatdan** [comment]
I Disagree,  All INSTALL is for is to launch a script/tooling shipped within the container with a SPC container mode, that script should figure out what kind of OS it is on and setup the appropriate mechanism for installing the application.  Balkanizing these commands helps now one.

In most cases I believe RUN should not be included, it really is only there for complex docker commands and I think tools like K8s or systemd unit files should handle most of the options in running an application.  I see INSTALL/UNINSTALL to be the equivalent of Post/Postun scripts in RPM.  Packager should do whatever he wants.

Having a packager having to add labels for each Distribution is just going to cause no one to use the tooling.  

Worse case we use a Generic RUN command and then add OS Specific run commands if this proves to be a problem.

**Comment by rhatdan** [comment]
I agree that labels being inherited is a problem, but this is the best we have for now.  As we go forward we can make this feature better, but we need to get some agreement on Generic Names now.

Lets ignore the implementation, since I see these as being defacto standards for other container formats.

**Comment by larsks** [comment]
It seems like, as implemented right now, both RUN and INSTALL are extremely docker specific (because they represent complete docker command lines), which seems unlikely to be useful with other container formats.

**Comment by rhatdan** [comment]
Well I would say they only support a single container tool.  Since they could run any command.

systemd-nspawn ...  

Should work fine.  Moving them to a more generic command would be very difficult.  But allowing multiple container command runs would work.  DockerRun, NspawnRun, RocketRun...

**Comment by rhatdan** [comment]
Any further comment on this?  Going through old issues trying to clean them up

**Comment by larsks** [comment]
I got nothin'.
