### ISSUE TITLE
"atomic.sh" script is broken or "atomic run" is broken

### ISSUE THREAD

**Issue by larsks** [projectatomic/atomic#44]
The `atomic.sh` script attempts to execute the following:

    atomic run --spc ${TOOLSIMG} "$@"

With the current revision of the `atomic` script itself, this will fail with:

    Container 'rhel-tools-spc' must be running before executing a command into it.
    Execute the following to create the container:
    atomic run --SPC --name rhel-tools-spc larsks/rhel-tools

...unless the container is already running.  Fundamentally, I think we need to support `atomic run <image> <command>` regardless of whether or not the container is already running.

**Comment by jeremyeder** [comment]
@davidegts also raised this during the SA training in March.  Agreed this behavior is surprising.

**Comment by rhatdan** [comment]
Moving the discussion to https://github.com/projectatomic/atomic/issues/75
