### ISSUE TITLE
Add more functionality to "atomic ps"

### ISSUE THREAD

**Issue by yuqi-zhang** [projectatomic/atomic#470]
Currently the "atomic ps" command only accepts 3 extra arguments (not counting help). Some potentially useful sub-commands to enhance functionality could be:

  --quiet - display only the IDs
  --no-trunc - don't truncate output
  --sys - only display system containers, or better,
  --filter - filter content
  or some variation of --format="format-string"

Originally, this was intended to help fix bash auto-complete, which did not display atomic containers and images. But a workaround fix has been provided here: https://github.com/projectatomic/atomic/pull/467 . Regardless, extra options to increase/manipulate information would be helpful.

If any of these seem useful, or should be named differently, please point it out.

**Comment by rhatdan** [comment]
These sound good to me.

**Comment by giuseppe** [comment]
I like the idea of `--filter="all|system|docker"` instead of `--sys`

**Comment by runcom** [comment]
+1 to a filter flag instead of so many other flags (ala docker)

**Comment by yuqi-zhang** [comment]
Ok, thanks for the comments!

**Comment by rhatdan** [comment]
If we add these filters flags, please do it for other atomic calls, so we are consistent.

atomic images --filter ...

**Comment by yuqi-zhang** [comment]
images currently only has --no-heading and --prune at the moment, should probably be expanded as well. For example, docker images supports: all, digests, filter, format, no-trunc, quiet

**Comment by rhatdan** [comment]
Right we need them to match.

**Comment by yuqi-zhang** [comment]
Working on adding similar functionality to images as well, will close issue once that is done.
