### ISSUE TITLE
atomic install --system issues on fedora 24

### ISSUE THREAD

**Issue by aveshagarwal** [projectatomic/atomic#471]
I built etcd image from here: https://github.com/aveshagarwal/etcd-container

atomic run etcd works fine but running it with system flag fails:

```
#atomic install --system --name=etcd1 etcd
HTTPSConnectionPool(host='etcd', port=443): Max retries exceeded with url: /v1/_ping (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7fa533da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by aveshagarwal** [comment]
same issue with flannel container.

**Comment by giuseppe** [comment]
how did you import it into the OSTree repository?

assuming you build it locally:

# docker build -t etcd .
# atomic pull docker:etcd  ## the docker: prefix means to pull from the local Docker
# atomic install --system --name=etcd1 etcd

**Comment by aveshagarwal** [comment]
@giuseppe if its locally built, why I have to do atomic pull?

**Comment by aveshagarwal** [comment]
@giuseppe Also, is it documented somewhere that even with locally built images, one has to perform atomic pull?

**Comment by giuseppe** [comment]
@aveshagarwal system containers use an OSTree repository as storage, not Docker.

Not really, even the part that locally built images are supported is not documented well, I will work on this

**Comment by aveshagarwal** [comment]
@giuseppe thanks. Please see this also https://github.com/projectatomic/atomic/issues/472

**Comment by aveshagarwal** [comment]
@giuseppe Without locally built images, how is one supposed to the development and testing?

**Comment by yuqi-zhang** [comment]
FWIW, I just push my system container images to my docker hub repo, which atomic install --system will pull from by default. Doing a docker build does build an image locally, and if it exists in the ostree repo, it *should* not pull from docker hub anymore.

**Comment by aveshagarwal** [comment]
@giuseppe I checked various options in atomic and ostree CLIs but not sure how to remove an imported image from ostree repo?

**Comment by yuqi-zhang** [comment]
I do "ostree refs --delete <image>" and "atomic images --prune", not sure if that's what you're looking for.

**Comment by aveshagarwal** [comment]
@yuqi-zhang thanks  

Initially I tried 
```
ostree refs --delete etcd
ostree refs --delete etcd:latest
ostree refs --delete  c867ad871ce2
```
Nothing worked. But then `ostree refs --delete ociimage/etcd-latest`  worked.

**Comment by yuqi-zhang** [comment]
@aveshagarwal np, I'll try to write up a quick guide on what we have now and how to get it to work, maybe it'll be helpful for people who want to take a look (I'm very new to all this).

**Comment by rhatdan** [comment]
Cleaning up atomic issues.

@aveshagarwal @giuseppe @yuqi-zhang Can I close this?

**Comment by aveshagarwal** [comment]
@rhatdan thanks I just closed it.
