### ISSUE TITLE
process whiteouts in system container checkouts

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#491]
I don't see us doing this?

**Comment by cgwalters** [comment]
And we should disable fsync and do a `syncfs()` after

**Comment by giuseppe** [comment]
oh I assumed it was enough to use the UNION_FILES overwrite mode.  I am going to fix that.  Thanks for reporting it.

About `syncfs`, I had a look at it before and I could not find a nice way to do it in Python.  The `os` module has only `sync`.  I didn't really like the alternatives: external process or load libc via ctypes.  Do you have any suggestions?
