### ISSUE TITLE
atomic image prune breaks test_system_containers

### ISSUE THREAD

**Issue by yuqi-zhang** [projectatomic/atomic#496]
The newly merged PR: https://github.com/projectatomic/atomic/pull/492 causes test_system_containers to fail:

+ /usr/bin/coverage run --source=./Atomic/ --branch --append atomic images prune
++ grep -c ociimage
++ ostree --repo=/vagrant/atomic/.tmp.BmEnxquwkq/repo refs
+ OUTPUT=6
+ teardown

From a glance, the new prune is not removing dangling ociimages? Apparently the upstream tester did not have runc, which caused the test to be skipped entirely (and thus pass). But this is locally reproducible when running make test.

**Comment by jlebon** [comment]
Just a note here. I'm in the process of updating the tester to F24. Will also include runc at that time.

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
working on it, will post a patch soon

**Comment by jwhonce** [comment]
@giuseppe Thanks for catching that, let me know if I can help.
