### ISSUE TITLE
migrate-dir not being cleaned up on failure

### ISSUE THREAD

**Issue by yuqi-zhang** [projectatomic/atomic#500]
During test_migrate, if atomic storage import is not completed, the generated migrate-dir is not cleaned up. @shishir-a412ed PTAL.

**Comment by shishir-a412ed** [comment]
Related to #498.

Thanks !
Shishir

**Comment by rhatdan** [comment]
Lets get this fixed so tests work again.

**Comment by rhatdan** [comment]
Fixed in atomic-1.13
