### ISSUE TITLE
[bug/feature not implemented] atomic verify does not work on a system image

### ISSUE THREAD

**Issue by stephen679** [projectatomic/atomic#504]
After doing a fresh clone of [atomic](https://github.com/projectatomic/atomic), I tried to verify an image pulled using `atomic pull`, which ultimately is an image stored in the ostree repo.  The result was that `atomic verify` could not find that image, which then caused the program to crash.

Expected:
output telling user if an image has new versions available

Actual (with `--debug` flag):
```
[schung@localhost atomic] $ sudo ./atomic --debug verify fedora
91c7a0700c79df6bb9ed3c455d1d04e4d77abf1db0148a5ca03ecb760f8bc6ec
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./atomic", line 691, in <module>
    sys.exit(_func())
  File "/home/schung/Desktop/atomic/Atomic/verify.py", line 43, in verify
    self.image = self.get_fq_name(self._inspect_image(iid))
  File "/home/schung/Desktop/atomic/Atomic/atomic.py", line 602, in get_fq_name
    if len(image_info['RepoTags']) > 1:
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Some other info:
```
[schung@localhost atomic] $ sudo ./atomic images list
   REPOSITORY         TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE      
   me/docker-whale    latest   b17b9070dbb1   2016-07-28 16:03   255.87 MB      Docker    
>  docker.io/ubuntu   15.04    d1b55fd07600   2016-01-26 12:48   131.27 MB      Docker    
>  training/webapp    latest   6fae60ef3446   2015-05-15 13:23   348.72 MB      Docker    
   fedora             latest   91c7a0700c79   2016-07-29 12:04                  System    
```
```
[schung@localhost atomic] $ docker inspect fedora:latest
[]
Error: No such image or container: fedora
```

**Comment by stephen679** [comment]
related to #331

**Comment by giuseppe** [comment]
currently verify does not support system images at all, so it is not related to #331.

I have done some refactoring of syscontainers.py and added a basic support for "atomic verify":

https://github.com/projectatomic/atomic/pull/506

One thing I have noticed is that `atomic verify` doesn't seem to work with a Docker registry v2, so the first step would be to properly support it.  Once that is done, we can use it to better support system containers, which support only the Docker registry v2 manifest file.

The main difference is that there is no concept of 'Parent' layer anymore in the v2 format, and each image has a list of layers that are checked out sequentially.  This list is part of the manifest file, that is retrieved from the Docker registry using Skopeo, and stored in the OSTree commit metadata (`docker.manifest`).

System images stored in OSTree are then slightly different, starting from a manifest file + the layers that compose the docker image we do:

1) Fetch the manifest file (using Skopeo)
2) For each layer present in the manifest and not already present in the OSTree repository,
2.1) Fetch the layer (using Skopeo)
2.2) Commit it to OSTree
2.3) Tag it with a branch (`ociimage/SHA-LAYER`)
3) Write the manifest in a separate OSTree commit (in the metadata)
4) Tag it (`ociimage/IMAGE`)

Once the v2 format is better supported, we should be able to check that the system image 'Layers" are updated using the same mechanism.
