### ISSUE TITLE
Output filename(s) from atomic scanners

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/atomic#577]
User story: I have a 10 atomic scanners to run for images I want to process in my tooling foo. I have a configuration file / option where I specify in foo tooling the list of atomic scanners and names of output files per scanner. 
Can I have a way to specify the names of output files, the scanner is going to result? If I can specify the output filenames, right at the time of building the atomic scanner in way, I can get the output filenames from the atomic scanner image itself, it would minimize providing ad hoc information along with atomic scanners.

Does this make sense to have result information embedded right in atomic container itself? via LABEL or  whichever is feasible way?

**Comment by baude** [comment]
I'm not sure I fully grasp what you are wanting here.  But you can add additional bind mounts to a custom scanner.  You could read and write from the additional bind mounts as you wish.

**Comment by navidshaikh** [comment]
The scanner output some result in one or multiple files. Can we have a configuration option to specify those output filenames right while building the atomic scanner it self?

**Comment by baude** [comment]
When a scan completes properly, atomic points to the directory to where all the files end up.  This is during run not build.

**Comment by navidshaikh** [comment]
> When a scan completes properly, atomic points to the directory to where all the files end up. This is during run not build.

Thats correct, as per scanner the directory can contain multiple files [log, debug, results] etc. Given that I am using atomic scanners in a tooling / service,  I do not want to parse stdout everytime there is a completed scan. Also, I'll have to explicitly (hardcod) the output file names to parse the scanner results.

The proposed idea is to, have a config option (while building the scanner itself) to specify (all) the output file names (which can include, result, debug, log files etc). Having this config option with values for output file names, I can concatenate the output directory and output result file name(s) to parse the results from scanner, rather traversing or hardcoding the result filenames in my tooling.

**Comment by baude** [comment]
Example please?

**Comment by baude** [comment]
@navidshaikh  is this still relevant

**Comment by navidshaikh** [comment]
> @navidshaikh is this still relevant

I did not really create a scanner which will create multiple files as a result. Closing the issue, will re-raise if I found a use case.
