### ISSUE TITLE
Find alternative way to determine an image's fully qualified "name"

### ISSUE THREAD

**Issue by baude** [projectatomic/atomic#578]
@mtrmac has correctly pointed out that using the repotags from inspection of a local image is not a reliable way to determine the fully qualified name of an image.

i.e. docker inspect busybox; massaging repotags to determine docker.io/library/busybox.

Alternative suggestions would be to write a subcommand for skopeo that only does that or write the logic from docker/docker/reference.go to Python.

For reference,  https://github.com/projectatomic/skopeo/blob/master/cmd/skopeo/inspect.go#L74 through https://github.com/containers/image/blob/master/docker/docker_image.go#L31 , no remote data is being used

**Comment by rhatdan** [comment]
@baude Where are we going with this one?

**Comment by baude** [comment]
Fixed in https://github.com/projectatomic/atomic/pull/687
