### ISSUE TITLE
ostree refs --delete behavior, is it a bug or intentional?

### ISSUE THREAD

**Issue by aveshagarwal** [projectatomic/atomic#592]
On rhel7.3 beta, I created a docker image: `etcd:latest`.
Then I imported it into ostree: `atomic pull docker:etcd`
After that, when I try to delete it using ostree refs --delete, I tried following that dont work, i.e. `atomic images list` still shows the image etcd:

`#ostree refs --delete ociimage/etcd`  returns silently.

`ostree refs --delete ociimage/etcd:latest` outputs following error:
`error: Invalid refspec ociimage/etcd:latest`

But the following  (see the `-` in etcd-latest) works, and `atomic images list" does not show the image:
`ostree refs --delete ociimage/etcd-latest`

Is it intentional syntax to have `-` between etcd-latest or a bug?

**Comment by aveshagarwal** [comment]
@giuseppe

**Comment by aveshagarwal** [comment]
I just checked
`atomic images delete etcd:latest`
`atomic images delete etcd`

seems to work correctly.

**Comment by yuqi-zhang** [comment]
This is intentional, if you list the refs with `ostree refs`, you will see that it is saved in the `$OSTREE_OCIIMAGE_PREFIX/$image-$tag` format. Delete parses your input into that format and thus does not need the "-".

**Comment by rhatdan** [comment]
So should we close this issue?

**Comment by aveshagarwal** [comment]
I am fine with closing this issue as `atomic images` cli are working correctly.
