### ISSUE TITLE
Atomic sign --directory does not maintain full signature path

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#615]
Expected: `atomic sign --directory /mnt/path ...` should prefix the normal path with `/mnt/path` and provide a directory tree in this form: `<registry_uri>/<repository>/<image@sha256:manifestdigesthash>/signature-<int>`.

Actual: signature file lands as `/mnt/path/signature-1` 

cc @baude

**Comment by rhatdan** [comment]
Could you write a patch?

**Comment by baude** [comment]
Ok, I'm on it.

**Comment by baude** [comment]
Function added in -> https://github.com/projectatomic/atomic/pull/614

**Comment by rhatdan** [comment]
I think you meant https://github.com/projectatomic/atomic/pull/617
