### ISSUE TITLE
Need documentation/usage on atomic sign "default-docker"

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#616]
I got this error message:

```
$ sudo atomic sign --sign-by corp@example.com docker.io/openshift/hello-openshift
Unable to associate docker.io/openshift/hello-openshift with configurations in /etc/containers/registries.d/ and no 'default-docker' is defined.
```

It looks like we need to incorporate this document[1] into our man page(s) (atomic-sign?) and ensure that the 'default-docker' edge case is not the first user experience.

[1] https://github.com/containers/image/blob/master/docs/registries.d.md

**Comment by aweiteka** [comment]
Based on conversation we'll address this by shipping file `/etc/containers.registries.d/default.yaml`

        default:
          # sigstore: file:///var/lib/atomic/sigstore
          sigstore-staging: file:///var/lib/atomic/sigstore

        # docker:
        #   privateregistry.com:
        #    sigstore: http://privateregistry.com/sigstore/
        #    sigstore-staging: /mnt/nfs/privateregistry/sigstore

**Comment by rhatdan** [comment]
Do we have a pull request to add this to atomic.  Should make this be installed using make install.

**Comment by aweiteka** [comment]
We discussed adding a config man page to cover registires.d and policy.json. Any opinion what that might be named? @baude

**Comment by rhatdan** [comment]
man policy.json 
man registries.yaml

**Comment by aweiteka** [comment]
partially resolved with #633

**Comment by aweiteka** [comment]
@rhatdan to resolve this we have a need for two shared man pages between skopeo and atomic.

* `man registries.yaml` https://github.com/containers/image/blob/master/docs/registries.d.md
* `man policy.json` https://github.com/mtrmac/image/blob/888f007f0b7f04e023149100f89a4de8210772ad/docs/policy.json.md

How would this work? Should I put these in skopeo? The source is in containers/image.

cc @mtrmac

**Comment by mtrmac** [comment]
Yeah, this is ugly ATM; `containers/image` does not have a RPM, and the `skopeo` vendoring process does not pull `.md` files.

We could modify `skopeo/hack/vendor.sh` to keep `*.md` around, and package that in `skopeo`; we could modify `skopeo/Makefile` to pull in the documentation explicitly; we could do all of this in the RPM spec.  None of these is extraordinarily beautiful but any of them would work fine.
