### ISSUE TITLE
atomic trust will not create or edit empty policy.json 

### ISSUE THREAD

**Issue by ddarrah** [projectatomic/atomic#625]
If the file is missing or has no valid json content, tool will not run.  The argument could be made that it should never edit a corrupted file, but it would be fairly straightforward to create a new one if the file is not there.  This would allow a user a simple way to reset by blowing it away and adding new trust with the tool.

**Comment by aweiteka** [comment]
@ddarrah this should be fixed with #628

**Comment by rhatdan** [comment]
Fixed in atomic-1.13
