### ISSUE TITLE
Should atomic be able to create systemd unit files?

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/atomic#64]
Should we add functionality to create systemd unit files directly into atomic so that they are as simple as a proper label?

See manual effort described here: http://www.projectatomic.io/blog/2015/06/running-cockpit-as-a-service/

**Comment by rhatdan** [comment]
That would be difficult, since each unit file is different. We could generate a template, but I am not sure if this is worth much. 

What were you thinking?

**Comment by bexelbie** [comment]
It seems that we could transform the RUN label (and others as appropriate) into a templated init file.  That said, I can understand us not wanting to have to support every init system on the planet ...

The value I see is that the container designer has fewer things to have to manage

**Comment by rhatdan** [comment]
Perhaps we should just fix atomic run to work the way you expect or to add a flag to have that happen.
Then you would only need to have atomic run --init MYAPP
And it would run the application.

There seems to be two use cases for atomic run, I will label these as the tools container use case and the service use case.

Atomic run was originally designed for running tools containers. 

In tools container world, you create one container, and every atomic run ends up putting new processes into the same container.  The nice thing about this model is if I do a yum update inside of the container to add a new package, a future atomic run sees the new packages.  This is how people use it on rhel-tools container on atomic.

Seems lots of other people want to do the service model, where they expect each atomic run to create a new container for the duration of the run.  This I believe would more closely match what you are after.

**Comment by bexelbie** [comment]
I would offer a third case, more related to #24, single use non-service containers.

For example, I recently needed to have yaml2ical briefly.  I don't want it to "litter" my HD with libraries that may conflict with my other dev tools.  The simplest solution seemed to be to create a little container to execute it.  I have a few wish list items for this that I can add here or in #24 or some where new.  But it is a case where we want a run on a container that will never be inited and will never be -d'ed.

**Comment by rhatdan** [comment]
@bexelbie Should we close this with discussion on atomic --spc/redesign?

**Comment by bexelbie** [comment]
@rhatdan .  Moving discussion to #75
