### ISSUE TITLE
trust delete should have a "rm sigstore" option

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#647]
Deleting trust removes it from the policy.json but leaves the registries.d config around. That's the correct default behavior but we should allow a user to cleanup the environment.

Not sure what to call this boolean flag...
```
$ atomic trust delete POLICY_NAME --sigstore
```

**Comment by rhatdan** [comment]
--remove?
```
man userdel
...
       -r, --remove
           Files in the user's home directory will be removed along with the home directory itself and the user's mail spool. Files located in
           other file systems will have to be searched for and deleted manually.

           The mail spool is defined by the MAIL_DIR variable in the login.defs file.
```
Seems quite similar.

**Comment by rhatdan** [comment]
@aweiteka is this something you are working on, or do you want me to do it.

Where do I find the sigstore data?

**Comment by aweiteka** [comment]
I'm not working on it.

This should remove the matching yaml section from a file in /etc/containers/registries.d/*. A call to util.get_registry_configs() will return the data you need.

I think this should be the **default** behavior, with an option to retain the sigstore URL, a less common use case. In other words, policy and sigstore are typically managed together IMO.

**Comment by rhatdan** [comment]
Ok, just set the --remove to default to yes.  Feel free to steel the stuff I have done so far.
