### ISSUE TITLE
"Name or service not known Error" executing atomic pull 

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic#648]
I am getting an error running atomic pull busybox (and other containers) on CentOS Atomic Host Continuous.

Reproducible on git master.  The issue started in atomic-1.12.3.4 but was not an issue on 1.12.2.10.

[cloud-user@cloud-6 ~]$ sudo atomic --debug pull busybox
Image busybox is being pulled to docker ...
[Errno -2] Name or service not known
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 54, in pull_image
    handler()
  File "/usr/lib/python2.7/site-packages/Atomic/pull.py", line 30, in pull_docker_image
    insecure = True if is_insecure_registry(self.d.info()['RegistryConfig'], strip_port(registry)) else False
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 680, in is_insecure_registry
    for r in get_ips_from_host(registry):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 674, in get_ips_from_host
    return list(set([x[4][0] for x in socket.getaddrinfo(_host, None)]))
gaierror: [Errno -2] Name or service not known

$ sudo atomic pull docker.io/busybox
Image docker.io/busybox is being pulled to docker ...
Incorrect Usage.

NAME:
   copy - 

USAGE:
   command copy [command options] [arguments...]

DESCRIPTION:
   

OPTIONS:
   --sign-by 	sign the image using a GPG key with the specified fingerprint
   

FATA[0000] flag provided but not defined: -remove-signatures 

$ sudo rpm -qa | grep atomic
atomic-1.12.3.4-1cd5ba96b749ea26b60f935dff62ef7818562bfd.01544d1575d272d5c47dbbb0ebd47cd57d682e7c.el7.centos.x86_64

**Comment by rhatdan** [comment]
You need to update your version of skopeo.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
https://github.com/projectatomic/atomic/pull/650 fixes this when it is merged.

**Comment by baude** [comment]
also, in the meanwhile, you should be able to provide a more complete image name and it should work.  for example, 'docker.io/library/busybox:latest'

**Comment by mike-nguyen** [comment]
Confirmed to be working with #650 and skopeo-0.1.14-0.6.

**Comment by cgwalters** [comment]
@baude @mtrmac  https://github.com/CentOS/sig-atomic-buildscripts/pull/155#issuecomment-248763392 ?

**Comment by baude** [comment]
Can someone verify this is fixed in the latest master branch and close if so?

**Comment by rhatdan** [comment]
Fixed in atomic-1.13.
