### ISSUE TITLE
Provide feedback during long push|pull ops

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#649]
It's concerning not to have any feedback when waiting for a long process. docker client gives lots of feedback for each layer operation.

**Comment by baude** [comment]
you need to direct this at skopeo.  atomic has no influence on this now that skopeo does the work.

**Comment by rhatdan** [comment]
@runcom @mtrmac PTAL

**Comment by runcom** [comment]
I didn't want to overload skopeo with fancy progress bars at the beginning, but we expose sizes for objects retrieved over the network so this could be feasible somehow. What kind of feedback are you looking for?

**Comment by rhatdan** [comment]
Probably a ui like docker pull.

**Comment by runcom** [comment]
> Probably a ui like docker pull.

please no :cry:

**Comment by rhatdan** [comment]
You can do something simpler.  I think Aaron would just like to see something indicating it did not freeze.

**Comment by runcom** [comment]
> You can do something simpler. I think Aaron would just like to see something indicating it did not freeze.

alright, I'll work on this tomorrow morning - I'd like to coordinate with @baude wrt how to handle skopeo's output though

**Comment by aweiteka** [comment]
Simple is good. Push/pull performance seems quite slow so we just need *something*. This can be deferred to when skopeo output is handled better in general. Error handling is probably a higher priority.

**Comment by mtrmac** [comment]
_Something_ definitely needs to happen; currently mentioned in https://trello.com/c/2aeFwpVK/185-8-signing-add-local-docker-daemon-as-a-target-for-push-pull-actions-in-skopeo , a skopeo issue wouldn’t hurt.

**Comment by runcom** [comment]
> Something definitely needs to happen; currently mentioned in https://trello.com/c/2aeFwpVK/185-8-signing-add-local-docker-daemon-as-a-target-for-push-pull-actions-in-skopeo , a skopeo issue wouldn’t hurt.

we would need support in `image.Copy` I guess, something like passing an io.Writer where to write progress on

**Comment by mtrmac** [comment]
> we would need support in image.Copy I guess, something like passing an io.Writer where to write progress on

Yes, and perhaps even to pass it down to `GetBlob` and `PutBlob`, and ultimately to replace the `io.Copy`s in there with something which does progress reporting?

Or move to an `image.Copy`-provided `io.Writer` as the data transport interface (which would allow `image.Copy` to supply a progress-reporting implementation) instead of the current `GetBlob`-returned `io.Reader`.

Ultimately, instead of an `io.Writer` for text output, pass an interface capable of returning structured data, so that a GUI could be built on top? But then we end up with the complexity of `docker/pkg/progress` when all we need right now is an output to stdout.

---

Of course, right now, a single line of output per layer or so would already be a significant improvement. There are definitely dragons lurking when striving for perfection here, let’s tread lightly around them :)

**Comment by runcom** [comment]
@mtrmac I'm thinking about passing down a channel which notifies the callers about the current progress, nothing too much complex, just pass back strings that will be printed. Wdyt?

**Comment by mtrmac** [comment]
@runcom Honestly, whatever works for the output you need. We have made no ABI promise, so we can always make it infinitely complex later, if anyone can find that kind of spare time :)

**Comment by runcom** [comment]
Figured out the issue I was having on the master branch, though:
```
$ ./skopeo copy --sign-by runcom@redhat.com docker://fedora docker://runcom/busybox1:signed
Getting image source manifest
Getting image source signatures
Getting image source configuration
Uploading blob sha256:11a5107645d4ecb36e75d933576f5cdb52358bef385eac2c2d2a91af44ad4ad7
Uploading blob sha256:2bf01635e2a0f7ed3800c8cb3effc5ff46adc6b9b86f0e80743c956371efe553

```

**Comment by runcom** [comment]
alright, got pretty progress bars:
```
./skopeo copy --sign-by runcom@redhat.com docker://alpine docker://runcom/busybox2:signed
Getting image source manifest
Getting image source signatures
Getting image source configuration
Uploading blob sha256:7d23b3ca3463ae7d682961a1a07c1ec96d51fbbae90bef79207fad7385d4cb1e
 1.25 KB / 1.25 KB [===========================================================]
Uploading blob sha256:117f30b7ae3d50ac80e38e390a39f70848edcfc916127c2821604a8114c080aa
 738.02 KB / 2.20 MB [==================>--------------------------------------]
```

**Comment by rhatdan** [comment]
Excellent. Is this something going into containers/image?  Or skopeo?

**Comment by runcom** [comment]
@rhatdan some in containers/image (https://github.com/containers/image/pull/102) and some in skopeo (waiting containers/image PR merge to submit another one in skopeo)

**Comment by aweiteka** [comment]
I confirmed this is in upstream.
