### ISSUE TITLE
Update trust default policy so source type "docker-daemon"  is not rejected

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#653]
See discussion here: https://github.com/projectatomic/skopeo/issues/212

**Comment by rhatdan** [comment]
Do we need a pull request?  Isn't this something we are shipping now?

**Comment by aweiteka** [comment]
#658 
Can't merge yet; pending skopeo.

**Comment by mtrmac** [comment]
Isn’t the policy actually shipped in the skopeo package?

**Comment by aweiteka** [comment]
@mtrmac based on comments I think we'd like to ship with an insecure docker-daemon transport type. I would then close this PR and request that from skopeo. Thoughts?

**Comment by mtrmac** [comment]
Yeah, I can put that on the `docker-daemon` skopeo branch for now.

**Comment by rhatdan** [comment]
Looks like this is merged.

Fixed in atomic-1.13
