### ISSUE TITLE
(atomic push) sign_local TOCTOU vulnerability?

### ISSUE THREAD

**Issue by mtrmac** [projectatomic/atomic#660]
@baude PTAL

Per https://github.com/projectatomic/atomic/issues/644#issuecomment-249241376 :

Why does atomic push have the `sign_local` path at all, and how does it protect against the registry maliciously replacing the image between the time of the push an the time `Sign` fetches the remote manifest to decide what to sign? AFAICS it doesn’t, and this is a vulnerability.

**Comment by baude** [comment]
https://github.com/projectatomic/atomic/pull/662 addresses this issue.
