### ISSUE TITLE
atomic trust show --json should output parsed policy

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#661]
Currently `atomic trust show --json` just prints the policy.json file. More useful (and expected) is to output the same data in json format. We would then use a --policy-file flag to display the raw policy config. So this...

```
$ sudo atomic trust show
docker.io                           accept
docker.io/aweiteka                  signed   https://s3.amazonaws.com/aweiteka-sigstore
* (default)                         reject
```

Would output something like the policy file but with sigstore URI information:

```
{
	"default": [{
		"type": "reject",
                "sigstore-staging": "file:///var/lib/atomic/sigstore"
	}],
	"transports": {
		"docker": {
			"docker.io/aweiteka": [{
				"keyPath": "/etc/pki/containers/aweiteka@gmail.com",
				"keyType": "GPGKeys",
				"type": "signedBy",
				"sigstore": "https://s3.amazonaws.com/aweiteka-sigstore"
			}],
			"docker.io": [{
				"type": "insecureAcceptAnything"
			}]
		},
		"atomic": {}
	}
}
```

**Comment by rhatdan** [comment]
So currently we print everything but the signstore line?

**Comment by aweiteka** [comment]
> So currently we print everything but the signstore line?

Yes. I think this is lower priority than `atomic trust show REGISTRY`, which would show the evaluated policy given the scope. For example...

```
$ atomic trust show docker.io
docker.io              reject
$ atomic trust show registry.example.com
registry.example.com    signedBy foo.pub,bar.pub https://sigstore.example.com
```
