### ISSUE TITLE
Review trust policy auto-config use case

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#669]
Today (v1.12.5) we look for and inspect a special image called "sigstore" for image label metadata that defines trust policy for a REGISTRY/REPO. I think there's real value in automatically configuring a **standard policy** for a registry scope. The security concern is that we also install the public key for the user.

An alternative would be to automatically configure policy but require the public key be downloaded by some other trusted means: sneaker net, RPM, curl https://URI, etc. Thoughts?

/cc @mtrmac

**Comment by mtrmac** [comment]
What does “automatically configuring a standard policy” mean exactly?

At a first glance, this would be undesirable in cases where the policy is set up as “only images with IT-created approval signature can be run”, or “only images from these three approved vendors can be run” (on the production cluster) — but that really depends on what “automatically configuring a policy” means.

**Comment by aweiteka** [comment]
> What does “automatically configuring a standard policy” mean exactly?

At a minimum it means with a default "reject" rule, this policy will ensure you can successfully get the image: associating public key for this registry and where to download the signature files (sigstore). As usage matures we can investigate handling complexity.

Can we agree that users or organizations with more complex policy requirements will not be using this feature?

**Comment by mtrmac** [comment]
I still don’t know what “automatically configuring” means here. Could you walk me through the initial state, the commands, what happens automatically based on what criteria, the end state? What behavior change are you proposing to what component?

> Can we agree that users or organizations with more complex policy requirements will not be using this feature?

So this would be "automatic but opt-in”? “Automatic but opt-out”?

**Comment by aweiteka** [comment]
> So this would be "automatic but opt-in”? “Automatic but opt-out”?

Currently it's "automatic but opt-out" via atomic.conf `discover_sigstores: true`.

> What behavior change are you proposing to what component?

I'm trying to address the need to automate policy configuration while still maintaining security. I see no need to change how we automate policy configuration. What is problematic from a security point of view is automating download and install of a public key. This discussion is about possibly decoupling the policy configuration from installing the public key.

We could just delay this discussion to when we have more user perspective.

**Comment by mtrmac** [comment]
>>   What behavior change are you proposing to what component?

> I'm trying to address the need to automate policy configuration while still maintaining security.

 Could you walk me through the initial state, the commands, what happens automatically based on what criteria, the end state? What behavior change are you proposing to what component?

**Comment by mtrmac** [comment]
(I really have _no idea_ what this ticket is about.)

**Comment by aweiteka** [comment]
No motivation to change current behavior. Closing.
