### ISSUE TITLE
Atomic push does not handle '--insecure-registry 0.0.0.0/0'

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#670]
atomic v1.12.5

INSECURE_REGISTRY='--insecure-registry 0.0.0.0/0'

```
$ sudo atomic --debug push --sign-by aweiteka@redhat.com 10.3.11.254:5000/aweiteka/hello-world:latest
Namespace(_class=<class 'Atomic.push.Push'>, activation_key=None, assumeyes=False, debug=True, func='push', gnupghome=None, image='10.3.11.254:5000/aweiteka/hello-world:latest', password=None, pulp=False, reg_type=None, repo_id=None, satellite=False, sign_by='aweiteka@redhat.com', url=None, username=None, verify_ssl=None)
Registry Username: 
Registry Password:

Signing with 'aweiteka@redhat.com'

[Errno -2] Name or service not known
Traceback (most recent call last):
  File "/bin/atomic", line 186, in <module>
    sys.exit(_func())
  File "/usr/lib/python2.7/site-packages/Atomic/push.py", line 168, in push
    insecure = True if util.is_insecure_registry(self.d.info()['RegistryConfig'], util.strip_port(reg)) else False
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 690, in is_insecure_registry
    for j in get_ips_from_host(i):
  File "/usr/lib/python2.7/site-packages/Atomic/util.py", line 674, in get_ips_from_host
    return list(set([x[4][0] for x in socket.getaddrinfo(_host, None)]))
gaierror: [Errno -2] Name or service not known
```

**Comment by baude** [comment]
please report

python -c 'import docker; c = docker.Client(); print(c.info())'

**Comment by aweiteka** [comment]
{u'ContainersPaused': 0, u'Labels': None, u'ClusterAdvertise': u'', u'ContainersRunning': 0, u'NGoroutines': 27, u'LoggingDriver': u'json-file', u'OSType': u'linux', u'HttpProxy': u'', u'DriverStatus': [[u'Pool Name', u'VolGroup00-docker--pool'], [u'Pool Blocksize', u'524.3 kB'], [u'Base Device Size', u'10.74 GB'], [u'Backing Filesystem', u'xfs'], [u'Data file', u''], [u'Metadata file', u''], [u'Data Space Used', u'1.768 GB'], [u'Data Space Total', u'13.6 GB'], [u'Data Space Available', u'11.83 GB'], [u'Metadata Space Used', u'299 kB'], [u'Metadata Space Total', u'46.14 MB'], [u'Metadata Space Available', u'45.84 MB'], [u'Udev Sync Supported', u'true'], [u'Deferred Removal Enabled', u'true'], [u'Deferred Deletion Enabled', u'true'], [u'Deferred Deleted Device Count', u'0'], [u'Library Version', u'1.02.107-RHEL7 (2016-06-09)']], u'OperatingSystem': u'Red Hat Enterprise Linux Server 7.2 (Maipo)', u'Containers': 0, u'HttpsProxy': u'', u'BridgeNfIp6tables': True, u'MemTotal': 512786432, u'Driver': u'devicemapper', u'IndexServerAddress': u'https://registry.access.redhat.com/v1/', u'ClusterStore': u'', u'InitPath': u'', u'ExecutionDriver': u'native-0.2', u'Registries': [{u'Name': u'registry.access.redhat.com', u'Secure': False}, {u'Name': u'docker.io', u'Secure': True}], u'SystemStatus': None, u'OomKillDisable': True, u'PkgVersion': u'docker-common-1.10.3-55.el7.x86_64', u'SystemTime': u'2016-09-30T17:45:06.494178008-04:00', u'Name': u'rhel-cdk', u'CPUSet': True, u'RegistryConfig': {u'InsecureRegistryCIDRs': [u'0.0.0.0/0', u'127.0.0.0/8'], u'IndexConfigs': {u'atomic-registry.usersys.redhat.com:5000': {u'Official': False, u'Name': u'atomic-registry.usersys.redhat.com:5000', u'Secure': False, u'Mirrors': []}, u'registry.access.redhat.com': {u'Official': False, u'Name': u'registry.access.redhat.com', u'Secure': False, u'Mirrors': []}, u'10.3.11.254:5000': {u'Official': False, u'Name': u'10.3.11.254:5000', u'Secure': False, u'Mirrors': []}, u'docker.io': {u'Official': True, u'Name': u'docker.io', u'Secure': True, u'Mirrors': None}}, u'Mirrors': None}, u'ContainersStopped': 0, u'NCPU': 1, u'NFd': 17, u'Architecture': u'x86_64', u'CpuCfsQuota': True, u'Debug': False, u'IndexServerName': u'registry.access.redhat.com', u'ID': u'4BXC:F6LD:XATI:247I:PPIM:VZI5:DXM6:TMZ6:5OJM:C6DP:LCBJ:AGBF', u'IPv4Forwarding': True, u'KernelVersion': u'3.10.0-327.36.1.el7.x86_64', u'BridgeNfIptables': True, u'NoProxy': u'', u'InitSha1': u'6607cc35b2fbf036273f0890af4bcb35224417aa', u'ServerVersion': u'1.10.3', u'CpuCfsPeriod': True, u'ExperimentalBuild': False, u'MemoryLimit': True, u'SwapLimit': True, u'Plugins': {u'Volume': [u'local'], u'Network': [u'bridge', u'null', u'host'], u'Authorization': [u'rhel-push-plugin']}, u'Images': 10, u'DockerRootDir': u'/var/lib/docker', u'NEventsListener': 0, u'CPUShares': True}

**Comment by aweiteka** [comment]
@baude updated output with only single insecure-registry entry. Same failure.

**Comment by rhatdan** [comment]
@baude Any update on this?

**Comment by aweiteka** [comment]
This works with master source. Closing, unable to reproduce.
