### ISSUE TITLE
Add a "display" option that will show the command to be executed - similar to make -n

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/atomic#68]
It would be nice to be able to do something like

atomic run --display foo_container

and just see the actual docker command that will be executed without executing it.

**Comment by rhatdan** [comment]
I like the idea I am not sure of the option

@cgwalters @baude @willmtemple  thoughts

**Comment by rhatdan** [comment]
Obviously we would want this for other commands.

install, uninstall

**Comment by bexelbie** [comment]
@rhatdan yes for all commands :)

**Comment by willmtemple** [comment]
@rhatdan @bexelbie Definitely has a use case, but I'm not sure about adding it as a flag to atomic run. We already have atomic info to retrieve label information, so instinctively I want to add this as an arg to atomic info. Maybe an 'atomic info -o|--output LABEL foo_container' to filter label information? If it's an issue that RUN isn't always labeled, we could add --run, --install, --uninstall flags to atomic info that we guarantee to produce the *actual* commands that will be issued to the shell on atomic run, install, uninstall.

**Comment by bexelbie** [comment]
I am happy to see it be part of atomic info, but we need to make sure it is easy and as obvious as possible.

**Comment by rhatdan** [comment]
I don't think this is quite in info.  What bexelbie is saying, I believe is he wants to know what the following command would execute.

automic run --display -n foo fedora

Which is the line we currently print to the screen before executing the command.  This would allow him to see what command substitutions happened and whether or not his arguments look correct.

**Comment by bexelbie** [comment]
IMHO, we should add a print of the environment as well now that we have #66 merged.

**Comment by rhatdan** [comment]
I am not sure we have come to a conclusion on this.  

Do we want atomic run|install|uninstall --display or --test
which would just show you the command that would be run without actually running the command?

**Comment by bexelbie** [comment]
yes, something like --test or --display would be great.

**Comment by rhatdan** [comment]
@sallyom you want to take a stab at this?

**Comment by sallyom** [comment]
yes, of course, i'll start looking at it today.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/93 solves this issue.
