### ISSUE TITLE
add atomic list command ?

### ISSUE THREAD

**Issue by jeremyeder** [projectatomic/atomic#7]
Will atomic install grow a "default container" to pull ?  How is a user supposed to know what to do here?

atomic list could list available images, or possibly only ones that have a LABEL that atomic knows about...

Right now I need to switch over to the docker command to see what images are available.

**Comment by rhatdan** [comment]
I don't know.  One suggestion would be we do something like yum on atomic, where if you specify at the # prompt a command that does not exists, the tool goes out and attempts to install a OStools image, and run the command within.

strace -p 1234
The RHEL Atomic OS does not include this command will check the rheltools image for it.
Downloading rheltools
atomic run rheltools strace -p 1234

**Comment by rhatdan** [comment]
Well we really start to grow functionality here, do we want atomic search and atomic list?  

I have no problem adding these, but they would become more compelling if we had support for other formats then docker.  (rocket?) systemd-nspawn?

**Comment by LalatenduMohanty** [comment]
+1 to @jeremyeder . As we do project atomic command as the coherent entry point for atomic hosts.

**Comment by rhatdan** [comment]
So how should atomic list work?  Just list the container images on the host?

Atomic search just a pass through to docker search?

**Comment by jeremyeder** [comment]
Perhaps some meta-behavior...

For example, atomic list could also list out images that are docker formatted but not used by docker (early-docker).  BTW I like that idea.

**Comment by rhatdan** [comment]
I think I need more explanation...

**Comment by jeremyeder** [comment]
Right now we have to switch between atomic and docker commands fairly regularly. One of the gaps is figuring out which images exist.

My comment a few minutes ago was meant as a reply to your comment from March 4 wrt atomic list supporting alternate image formats, using an example of container images that are not controlled by the Docker daemon.

So, atomic list would be "meta" in that it would pass through to "docker images", and _also_ systemd-nspawn or rkt or whatever else.

**Comment by rhatdan** [comment]
@jeremyeder Checkout https://github.com/projectatomic/atomic/pull/82

**Comment by jeremyeder** [comment]
Thanks!
