### ISSUE TITLE
No uninstall for system containers?

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomic#705]
We appear to be missing any uninstall option for system containers:

-bash-4.2# atomic uninstall gscrivano/flannel
('Connection aborted.', error(111, 'Connection refused'))
-bash-4.2# atomic uninstall --system gscrivano/flannel
atomic: unrecognized arguments: --system
Try 'atomic --help' for more information.

Attn @giuseppe

**Comment by rhatdan** [comment]
What version of atomic?  I thought I saw a fix for this go by?  Would be in atomic-1.13.*

**Comment by jberkus** [comment]
Turns out basic uninstall works pending issues with the container.

However, I think we should accept and ignore the --system flag in uninstall, for symmetry.  It's confusting to the user to accept --system for install, but not for uninstall.

**Comment by rhatdan** [comment]
Should we require it?

**Comment by jberkus** [comment]
Given that we apparently don't need it, I'd say no.

**Comment by giuseppe** [comment]
we already support uninstall, but you need to do that by name as there can be more instances of the same image.

For example:
```
# atomic install --system --name=etcd1 gscrivano/etcd
# atomic install --system --name=etcd2 gscrivano/etcd
```
will install two containers `etcd1` and `etcd2` from the same image `gscrivano/etcd`.  You will need to refer to one of them when you uninstall, to uninstall `etcd1`:
```
atomic uninstall etcd1
```

In your case, as you probably have not specified a name, `etcd` is used by default from the name of the image, so you will need `atomic uninstall etcd`.

You can use `atomic containers list` to see what containers are currently installed.

**Comment by rhatdan** [comment]
Once we add container/storage as a backend for containers, this might get more complex.  Theoretically you could have two containers with the same name.  For example you could have a container etcd in docker and one on ostree.  We will need to figure this out going forward.

**Comment by giuseppe** [comment]
@rhatdan yes that is an issue and @yuqi-zhang is currently working on something for this issue, so that it is possible to specify what container we are addressing, if system container or docker container (or something else in the future).

**Comment by yuqi-zhang** [comment]
I am investigating this. Similar issues apply for images as well (i.e. you can have the same name for an image pulled to Docker and another pulled to ostree). If you invoke delete on that image name, it will first delete from ostree, and then on a second invoke it will delete from Docker.

I was thinking to allow:
1. Detect if there are duplicates, if there are, ask the user to specify
2. Allow user to specify system(ostree)/Docker as part of the command
3. If there are no duplicates and the user does not specify, delete it without complaining

**Comment by rhatdan** [comment]
I think we should add a --storage option which specified docker/ostree.  So a user can say remove one or the other.

We can maintain what we have now, except fail if there are multiple imaeges/containers with the same name and make the user specify the storage backend.

**Comment by baude** [comment]
There is:

```
atomic uninstall --storage ostree <image>
```
That should be sufficient to close this yes?
