### ISSUE TITLE
'atomic version' gives non-helpful error information

### ISSUE THREAD

**Issue by yuqi-zhang** [projectatomic/atomic#708]
When a user invokes version on a non-local system/docker image (e.g. 'atomic version asdf'), atomic will view the "asdf" as a remote docker repo and attempt to inspect with skopeo. This will cause an error:
`# atomic version asdf`
`ReturnTuple(return_code=1, stdout='', stderr='time="2016-10-13T14:29:23Z" level=fatal msg="error fetching manifest: status code: 401, body: {\\"errors\\":[{\\"code\\":\\"UNAUTHORIZED\\",\\"message\\":\\"authentication required\\",\\"detail\\":[{\\"Type\\":\\"repository\\",\\"Name\\":\\"library/asdf\\",\\"Action\\":\\"pull\\"}]}]}\\n" \n')`

Some other errors can occur such as: 
`# atomic version docker:gscrivano/hello-world`
`ReturnTuple(return_code=1, stdout='', stderr='time="2016-10-13T14:34:16Z" level=fatal msg="Error parsing reference: \\"docker:gscrivano/hello-world\\" is not a valid repository/tag" \n')`

Which is ugly and not very helpful. One potential way to remedy this is to let the user know a local image was not found and thus atomic will attempt a remote inspect, instead of directly telling the user "authentication required", etc.

**Comment by rhatdan** [comment]
Yes I think this is a bug.  atomic verify is supposed to be verifying the local image, if it does not exist, it should not attempt to pull the image.

@baude is looking at this code, right now so I will add this to the list of things to fix.

**Comment by baude** [comment]
@rhatdan actually this is 'version' code that is being reported on.  Quickly looking here, the code in question is:
```
        try:
            self.inspect = self.d.inspect_image(self.image)
        except NotFound:
            self.update()
            self.inspect = self.d.inspect_image(self.image)
```

It looks locally, if it cannot find it, it tries to "pull" the image.  It very much looks like the error that is being reported as non-helpful comes from skopeo trying to pull and image that does not exist.

This current approach is likely to be error prone because we no longer can benefit from the docker approach to pull the image.  Skopeo needs a fully-qualified image input.  Therefore, it will need to go through my new inspect code and then be pulled.

However, given your comment, do you want 'version' to pull the image if it does not exist locally?  I'm somewhat thinking the right approach here would be to error out saying the image does not exist locally (or cannot be found given the input).

Weigh in and I'll take care of it.

**Comment by giuseppe** [comment]
IMHO, I think it should not try to pull the image if it doesn't exist locally.

**Comment by rhatdan** [comment]
I agree, error out.

**Comment by yuqi-zhang** [comment]
Sorry I prematurely closed this, I have 2 other questions regarding this:

1. "atomic version" does not work with system images with this new change, since get_version will immediately check for layers in version, which only check for docker images. As a result it will just output: `Could not find any image matching <image>`
If we want "version" to display similar information to system containers I can add that.

2. images that are not tagged with "latest" works weirdly with version and info. Let's say I built a local image called local/test-image:v1

 - `atomic version local/test-image` will complain:
        > Could not find any image matching local/test-image

 - `atomic info local/test-image` will instead output: 
        > Found more than one image possibly matching 'local/flannel'. They are:

        > Refine your search to narrow results.

    and not actually give any suggestions.

The question being how we should correctly handle these cases.

And as a note, in the PR fixing the issue, the tests should be instead changed to "atomic info <image>" since it is testing for label information (which used to be displayed with version) if you want to re-enable them.

@baude @rhatdan @giuseppe  PTAL

**Comment by yuqi-zhang** [comment]
Also, since the error before was actually caused by skopeo in the function `info`, the error I reported at first still exists in "atomic info <non-existing-image>". Basically `atomic info` now does what `atomic version` used to do.

**Comment by giuseppe** [comment]
I have submitted a PR to address the system containers part:

https://github.com/projectatomic/atomic/pull/711

I confirm the other two issues are still present though.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/711 is merged

**Comment by yuqi-zhang** [comment]
Since "info" currently works the same way as Docker (i.e. Docker also does not detect non-latest tags) I think it's fine as is. The error information is a minor issue so I'll probably look into it along with duplicate naming. Will close issue unless something else comes up.
