### ISSUE TITLE
atomic help file in MarkDown format vs manpage format

### ISSUE THREAD

**Issue by bartockbat** [projectatomic/atomic#719]
https://github.com/projectatomic/atomic/blob/master/Atomic/help.py#L31

When creating an atomic help file, currently one must:
1. create the help file in MarkUp format
2. copy to the Docker container during build
3. convert the MarkUp file into a manpage file
4. for cleaup purposes, remove the conversion utility and the original MarkUp file from the built container, of course leaving the manpage file intact.

Could there be a provision for either accepting MarkUp format as a help file in the atomic host application?

OR

Building in the conversion utility to convert the MarkUp file on demand when a user types :

atomic help <container_name>

**Comment by rhatdan** [comment]
Then we would need to require a markup conversion tool.  Right now we only rely on '/usr/bin/groff" being available, in your scenario atomic tool would be required to pull in something like md2man to be installed
groff is required by man, so their is a great chance that it is installed.

@baude and I talked about this.  It would be cool if groff or someother tiny tool could convert markdown to man pages.
