### ISSUE TITLE
Versioning for Atomic?

### ISSUE THREAD

**Issue by jzb** [projectatomic/atomic#72]
Hey -- is there any versioning for the Atomic command/utility? I think it might be useful to start doing release #'s so we can describe differences between Atomic in Fedora releases, CentOS rebuild/4-week, etc. since there may be times when a release from Fedora has a feature whereas the CentOS rebuild does not. 

Thoughts?

**Comment by rhatdan** [comment]
Well we should have an rpm version when atomic package is separated out in 7.2, I believe it already is in fedora.

 rpm -q atomic
atomic-0-0.10.gite5734c4.fc23.x86_64

You want something more than this?

**Comment by bexelbie** [comment]
I can see some situations where it would be nice to be able to get a version string from atomic directly.  This is particularly true when we move to seeing it packaged on other distributions.  If nothing else, we could tag releases in the tree.

**Comment by rhatdan** [comment]
Well atomic version means something different, but I guess we could add a 
atomic -v command, but I am not sure what version we would put in here and how we would get how we would updated it.

**Comment by bexelbie** [comment]
Can we just declare some releases based on feature set getting added?  Maybe move it to 1.0 at this point?

**Comment by jzb** [comment]
@rhatdan Yeah, as @bexelbie mentioned, it'd be good to be able to do an "atomic -v" and return a string we can use to identify the release. 

The RPM version helps, though - as long as we can get that, and it identifies the release, that should be good. 

It might be easiest to just use a date-based release number? But, I'll leave release versioning discussions to the maintainers :-)

**Comment by rhatdan** [comment]
I have a patch that simply adds the VERSION flag, but I am undecided on what the VERSION should be.  Whether or not it should be version or build date. 

We could easily change the MAKE file to modify the code to change the VERSION.

@cgwalters @lsm5 

Thoughts.

**Comment by bexelbie** [comment]
If we use a date, could it be the last commit date or something else that wouldn't change based on when downstreams actually built the package?

**Comment by cgwalters** [comment]
I version most things now like `${YEAR}.${SERIAL}`, where `${SERIAL}` starts at 0 and increments each release.  It's the "compatible with rpm/dpkg and doesn't require any thought" model.

**Comment by rhatdan** [comment]
Do you do this via each commit, or via the Makefile?

**Comment by cgwalters** [comment]
With autotools, in `configure.ac`.  I don't have an automated link between the git tag and what appears in the source.  Though others do that.

**Comment by rhatdan** [comment]
@lsm5 What do you think?  Not a big fan of sucking in autotools, for something we are simply doing with Makefile and setup.py.  We are currently using the github tag, but we would still need the incrementing serial to show which is newer.

**Comment by cgwalters** [comment]
Doesn't need autotools, just a mechanism to inject something into the code.  I'd imagine setuptools has something for this.

**Comment by LalatenduMohanty** [comment]
What about doing doing releases through github [1] i.e. using "annotated tags"?
[1] https://github.com/blog/1547-release-your-software

**Comment by LalatenduMohanty** [comment]
Having released versions of atomic will help me track which version of atomic will have  the pull request https://github.com/projectatomic/atomic/pull/65 and which version of Fedora will have it? OR RHEL atomic version have it or not ?

**Comment by rhatdan** [comment]
I like the idea.  We just got to come to a conclusion or someone needs to submit a patch.

**Comment by bexelbie** [comment]
It looks like the git base released methodology doesn't directly need a patch, just one or more committers who will manage the release process.  We do need a patch to embed the version number somewhere in the code though.  Do you want me to work up a patch on that?  If so, have we settled on a version numbering scheme?  I personally vote for major.minor-serial and we can declare the next release to be 1.0-0 :)

**Comment by lsm5** [comment]
LGTM what @LalatenduMohanty said.

@bexelbie setup.py now includes a version number in it.

**Comment by rhatdan** [comment]
Problem there is no link between setup.py and what atomic -v shows.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/101

I added this patch, but this still does not fix the setup.py versus atomic command, I guess we could have setup.py modify the version on install.

**Comment by rhatdan** [comment]
atomic -v 

Now shows the version and we add it via setup.py.
