### ISSUE TITLE
'atomic host status' is broken

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#726]
The internal CAHC tests shows that the `atomic host status` command isn't working any more.

The CAHC deployments jumped between the following two commits from git master:

a60a3fedadd9eaec549e0514b980fe74a1379f24 to 97dc6098a026072a1fd78ecdcadf38026e86b9b2

But in the commit history, I see that there were a bunch of commits between those two.  And they seem to be in the DBus code, so I suspect something is broken there.

Anyways, this is what `atomic host status` looks like on git master now:

```
# atomic --version
1.13.2
# rpm -q atomic
atomic-1.13.1.39-97dc6098a026072a1fd78ecdcadf38026e86b9b2.dd4522961a9990fd47096ad652d3b6d9059051d7.el7.centos.x86_64
# atomic host status
Usage:
  /usr/bin/rpm-ostree [OPTION...] COMMAND

Builtin Commands:
  compose
  db
  deploy
  rebase
  rollback
  status
  upgrade
  install
  uninstall

Help Options:
  -h, --help       Show help options

Application Options:
  --version        Print version information and exit

error: No command specified

```

**Comment by cgwalters** [comment]
See https://github.com/projectatomic/atomic/issues/725
