### ISSUE TITLE
should continue to execl rpm-ostree for `host`

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#730]
In https://github.com/projectatomic/atomic/pull/723/commits/125e33044a3d887272024fff6e70c787e80219fb
we changed:

```
-        os.execl("/usr/bin/" + cmd, *(args + aargs))
+        return util.check_output([ "/usr/bin/" + cmd ] + aargs)
```

This means the user doesn't see _any_ output until the command completes, when executed interactively.  This is an annoying regression.

**Comment by cgwalters** [comment]
Why are we exposing the Host command via DBus?  The chain here is rather silly, since of course rpm-ostree is just going to talk dbus to its daemon...

Basically unless there's a user of this, let's nuke it.

**Comment by cgwalters** [comment]
There's a bigger picture architectural issue here in that at some point, I'd like `host status` to say something meaningful about containers/docker/etc.  The appropriate place to integrate those is probably in the atomic command, not in rpm-ostree.   So if we did something like that we'd probably want a DBus API for it etc.

But let's not introduce complexity unless we need it.

**Comment by rhatdan** [comment]
The user would be cockpit, we are attempting to make all atomic commands available via cockpit, but as you point out interactive commands won't work.

**Comment by rhatdan** [comment]
I can change the code to indicate whether or not you are are running it from the console or via dbus.

**Comment by cgwalters** [comment]
Cockpit already talks to rpm-ostree directly, what would be the value in changing that?

**Comment by rhatdan** [comment]
Not sure.  I was just going through all of the Verbs of atomic to add dbus support.  If there is no value add to atomic host, then we can remove the patch.

**Comment by rhatdan** [comment]
Removed host from dbus interfaces.
