### ISSUE TITLE
atomic help only looks for "HELP" label

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic#753]
There is no "HELP" label listed here:
https://github.com/projectatomic/ContainerApplicationGenericLabels

However there is a "help" label. I suggest that `help.py` should check for `help` first, then fall back to the compatibility name `HELP`, when looking for a command to display image help.

**Comment by twaugh** [comment]
Changing the issue name.

This does not only affect HELP, but also INSTALL, UNINSTALL, STOP, and probably every label. None of these are defined as upper-case, and all of them are defined as lower-case. The atomic CLI *must* use the names specified in the label documentation.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/atomic/pull/754 Should fix this issue.

INSTALL, UNINSTALL, and STOP already try all cases.

**Comment by twaugh** [comment]
Oh yes, I hadn't seen `_get_args()` in the other cases.

**Comment by baude** [comment]
Is this ok to close?
