### ISSUE TITLE
atomic diff: also compare image metadata

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic#760]
When using 'atomic diff' to compare images, differences in image metadata are not reported (for instance, different environment variables, labels, entry points etc.).

The image metadata is represented in JSON, and it would be useful for 'atomic diff' to report *what* is different in addition to *that* things are different. It would be sufficient to have the key names that have different values (or are present/not present).

**Comment by baude** [comment]
@twaugh Would you mind testing my branch which should enabled this? 

https://github.com/baude/atomic/tree/diff_diff_json

Feedback in IRC would be fine or here.

**Comment by twaugh** [comment]
get_node_value() needs to handle the case where image2 does not have that node path. Maybe it needs to be compare_node_value().

Other than that, this looks great!

**Comment by twaugh** [comment]
One thing -- it seems like 'docker inspect' includes some runtime data as well as image-specific data. I don't know any way around that other than to examine the image configuration directly ('docker save' the output, find the manifest.json in that archive, find the `Config` key in that, then look for the JSON file with that name).

**Comment by twaugh** [comment]
I think `_get_node()` needs to handle LEFT having {'foo': { 'bar': { 'baz': 1 } } } and RIGHT having { 'foo': { 'bar': None } }.

Perhaps `if isinstance(image, dict) and get_val in image:`?

**Comment by baude** [comment]
Closed in https://github.com/projectatomic/atomic/pull/764
