### ISSUE TITLE
atomic diff: image filesystem comparison is shallow

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic#761]
When using 'atomic diff' to inspect differences between images, `filecmp.dircmp` is used. This performs a shallow comparison, meaning that files with the same time stamp and size are assumed to be identical.

As a result, these things may be reported as identical:
* symbolic links with different targets
* regular files with different content
* files with different permissions or ownership
* flies with different timestamps but identical content

With the exception of files with different timestamps but identical content, the other cases are very useful to report as they are likely to make the image behave differently.

**Comment by baude** [comment]
After talking wqith @twaugh , we agreed if we are going to do this, we should focus on: symlinks with different targets, regular files with different content,  and files with different perms or ownerships.

**Comment by rhatdan** [comment]
Sounds good, is this something we should look at mtree for or is this something we should put into atomic CLI?

**Comment by baude** [comment]
@rhatdan Yes, I plan to use go-mtree and have been doing some preliminary testing and patching of go-mtree  so that it works correctly.  Been also keeping vbatts up to date as well.

**Comment by baude** [comment]
Closing, re-open if you need additional function
