### ISSUE TITLE
Each D-Bus call on org.atomic adds an atomic_dbus.py process

### ISSUE THREAD

**Issue by larskarlitski** [projectatomic/atomic#763]
None of them owns the name `org.atomic`, which is why every call activates the program again.

**Comment by rhatdan** [comment]
@larskarlitski How would we do that?  Do we want the process to stay running?

**Comment by rhatdan** [comment]
I am not even sure how well atomic would work if it stayed up all of the time.

**Comment by larskarlitski** [comment]
> How would we do that? Do we want the process to stay running?

Sorry if the description wasn't clear: the main problem is that there are a lot of `atomic_dbus.py` processes running. They exit after a while, but none of them keeps owning the `org.atomic` name, which is why a new D-Bus call will activate another one of these processes.

> I am not even sure how well atomic would work if it stayed up all of the time.

D-Bus services usually stay running after activation and hold on to the name, because it's likely that additional requests come in. It breaks when sending multiple requests in quick succession: the second message might be lost if it is sent while the service is dropping the name.

Despite this race, it's common for services to exit after a period of inactivity.

**Comment by rhatdan** [comment]
Yes I understand the concept. I am worried about the atomic library that the atomic dbus service was not designed to handle multiple requiests within the same process.  I am not sure if we are allocation new classes for each call.

**Comment by larskarlitski** [comment]
The dbus service seems to have been written with that in mind, though. I've opened #770 to make the process keep the name, which fixes this bug.
