### ISSUE TITLE
Atomic commands fail if container with the same name already exists.

### ISSUE THREAD

**Issue by eriknelson** [projectatomic/atomic#765]
This is admittedly a bit of a corner case, but its bitten a number of us working on some tooling around atomic. It's almost certainly the root cause of a related issue that was closed some time ago: #271

We ended up in a scenario where an atomicapp container is already running, or has been run but not cleaned out of the containers list, atomic identifies it as already having existed and attempted to `exec` the container with the atomic command, like `--mode fetch --destination .`. This results in the following error: 

`exec: "--mode": executable file not found in $PATH`

**Steps to reproduce**

1) `atomic run fusordevel/etherpad-atomicapp --provider docker`. This will hang waiting for answer input.

2) In a new console, `atomic run fusordevel/etherpad-atomicapp --mode fetch --destination /tmp/etherpad-atomicapp`. This should fail with the resulting error.

I'm not sure what the desired behavior is here, but even if it's considered user error, I would expect it to be handled more gracefully. Effectively running `exec --mode blah` feels broken.

I discovered this stepping through, I had the specific branch repsonsible for this recently, will try to update with the respective lines.

**Comment by yuqi-zhang** [comment]
Could you provide more details? It is expected behavior for both docker and system containers to not allow duplicate naming. Are other commands failing because you attempted to run a container with a duplicate name?

**Comment by eriknelson** [comment]
It inspects the container and recognizes it as already running:
https://github.com/projectatomic/atomic/blob/master/Atomic/run.py#L80

Then it builds up the command and attempts to execute it in the running container: 
https://github.com/projectatomic/atomic/blob/master/Atomic/atomic.py#L209

I'm not positive since I'm not in a position to confirm this, but I suspect it's executing `docker exec -t -i etherpad-atomicapp --mode fetch --destination .`. If  I run this myself, it produces the exact error I mentioned above.

**Comment by rhatdan** [comment]
@baude will your redesign take care of this issue?

**Comment by baude** [comment]
No, but I did talk with Erik briefly on IRC and asked for more information as well.  I think he was working to provide a definitive test case exclusive of atomicapp.
