### ISSUE TITLE
python3 support for atomic

### ISSUE THREAD

**Issue by rkuska** [projectatomic/atomic#77]
Looking at atomic code it looks like that it is not python3 ready - `import ConfigParser` at  atomic/Atomic/config.py@2 , do you have any plans to fix Python3 incompatibilities (if there is more of them)? Or would you accept PR regarding this issue?

**Comment by rhatdan** [comment]
Sure we would accept these patches.

**Comment by bkabrda** [comment]
I'll send a PR for this.

**Comment by rhatdan** [comment]
Great thanks.
