### ISSUE TITLE
how to use atomic to migrate container from one host to another?specific command,please

### ISSUE THREAD

**Issue by timchenxiaoyu** [projectatomic/atomic#786]

**Comment by rhatdan** [comment]
@shishir-a412ed Is this something you would want to write up?

**Comment by shishir-a412ed** [comment]
@timchenxiaoyu I think I answered your question :)
https://github.com/shishir-a412ed/Docker-Migrate/issues/2#issuecomment-264876301

/cc @rhatdan

**Comment by shishir-a412ed** [comment]
@rhatdan I think we can close this issue.
