### ISSUE TITLE
tests: Destructive tests, such as test-storage, don't run for pull requests.

### ISSUE THREAD

**Issue by mvollmer** [projectatomic/atomic#808]
This probably caused us to miss #805, which I think is a big deal.

**Comment by rhatdan** [comment]
How do we turn these on?  @jlebon Is this something we should do?

**Comment by jlebon** [comment]
@rhatdan Let's try it out in:
https://github.com/projectatomic/atomic/pull/828

**Comment by jlebon** [comment]
This is fixed now in #828 (i.e. all tests are now run, though the storage test is currently failing).
