### ISSUE TITLE
provide a 'reset to defaults' for the trust policy

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#820]
When manipulating the trust policy, it is possible that you get to a situation where you want to get back to the original config without having to remove all the policies that may have been added.

I think it would be useful to have a command that would reset the policy to the default state in this case.

For example:

```
# atomic trust reset
This will remove all policies that have been added by the user.
Are you sure you want to reset the trust policy to the default state? (y/N)
```

**Comment by rhatdan** [comment]
Do we want to do anything other then reset the policy.json file?

**Comment by baude** [comment]
I think this was done in 650c961425078ad6289b8fa58e0fc5176c596471 ?
