### ISSUE TITLE
improve error messaging for unknown images

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#860]
While testing #856, I saw the following error messages for the case of an image that did not exist.  Note, these are a v1 registry and v2 registry respectively.

```
# ./atomic pull registry.access.redhat.com/rhel7/foobar
ReturnTuple(return_code=1, stdout='', stderr='time="2017-02-01T21:06:33Z" level=fatal msg="unknown: Not Found" \n')
[root@fedora25cloud-dev atomic]# ./atomic pull docker.io/foobar/foobar/foobar
ReturnTuple(return_code=1, stdout='', stderr='time="2017-02-01T21:06:57Z" level=fatal msg="unauthorized: authentication required" \n')
```

I understand that the content of the messages is correct for each case, but I believe they could be formatted correctly

**Comment by miabbott** [comment]
@baude Not sure if you introduced this or if it had existed already.

**Comment by baude** [comment]
They are messages from skopeo.  I might be able to hide them if preferred.  I figured this might come up.  @rhatdan opinion?

**Comment by rhatdan** [comment]
Lets fix this in skopeo.  @runcom Could you clean up this error message to print something for humans.

**Comment by runcom** [comment]
skopeo's output is nice and human readable to me.

```
14:41:43 [github.com/projectatomic/skopeo] ‹master› ./skopeo inspect docker://registry.access.redhat.com/rhel7/foobar
FATA[0002] unknown: Not Found
14:41:53 [github.com/projectatomic/skopeo] ‹master› ./skopeo inspect docker://docker.io/foobar/foobar/foobar
FATA[0002] errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```
should atomic clean that output by just printing what's inside `msg` in `ReturnTuple`?

**Comment by rhatdan** [comment]
Ok so skopeo is returning decent errors, it is atomic that is screwing them up?

**Comment by baude** [comment]
Right now, atomic is adding the tuple references and so forth.  I think I can reduce it to just the error from skopeo as seen.  I'll whip up a PR.

**Comment by baude** [comment]
https://github.com/projectatomic/atomic/pull/862

**Comment by baude** [comment]
https://github.com/projectatomic/atomic/issues/860 was merged.  can we close this?
