### ISSUE TITLE
Don't report '--system' as unrecognized option

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#866]
If `runc` is not installed and the user tries to `atomic install --system` a container, the command returns that the `--system` argument is unrecognized.

```
# rpm -q runc
package runc is not installed
# ./atomic install --system gscrivano/etcd
atomic: unrecognized arguments: --system
Try 'atomic --help' for more information.
```

Can we error out and inform the user they are missing the necessary subcommand? For example:

```
# ./atomic install --system gscrivano/etcd
This command requires that 'runc' be installed.
```

**Comment by miabbott** [comment]
In the positive case, it looks like this:

```
# rpm -q runc
runc-1.0.0-3.rc2.gitc91b5be.fc25.x86_64
# ./atomic install --system gscrivano/etcd                                                                                                                                          
Extracting to /var/lib/containers/atomic/etcd.0
systemctl daemon-reload
systemd-tmpfiles --create /etc/tmpfiles.d/etcd.conf
systemctl enable etcd
```

**Comment by miabbott** [comment]
@baude Pointed out that this may only affect non-RPM installs (since `runc` is a dependency of `atomic`), so it is debatable if many users will encounter this.

**Comment by rhatdan** [comment]
@giuseppe 
I don't think --system should require runc in the first place.  We should be able to run system containers without runc, docker-system container will work, in the future people might package up system containers to use chroot/system-nspawn/portable services.  So we should allow the use of --system.  Rpm pulling in runc is a good thing though.

**Comment by giuseppe** [comment]
@rhatdan yes, even if we are generating EXEC_START and EXEC_END based on runc (if it runs as root), I think we should not fail if runc is missing as system containers could be used with other backends as well.

**Comment by miabbott** [comment]
@giuseppe @rhatdan It sounds like this issue could be re-titled as: "Don't report --system as unrecognized option"

WDYT?

**Comment by rhatdan** [comment]
Sure.

**Comment by miabbott** [comment]
Based on the conversation above, we should always allow the user to specify `--system` when doing `atomic install`.  It will be up to them to provide the necessary backend (runc, chroots, portable services, etc)

**Comment by giuseppe** [comment]
isn't that raised only when ostree is not available?

**Comment by miabbott** [comment]
@giuseppe I'm seeing it with a missing `runc` pkg using Fedora 25 Cloud

```
# git branch
* master
# git rev-parse HEAD
18863140ff940d9c94455dca9d5334e0bbb17b16
# rpm -q ostree runc
ostree-2017.1-2.fc25.x86_64
package runc is not installed
# ./atomic install --system gscrivano/etcd
atomic: unrecognized arguments: --system
Try 'atomic --help' for more information.
```

**Comment by giuseppe** [comment]
@miabbott is ostree installed?

**Comment by giuseppe** [comment]
yes, sorry, I misread your log

**Comment by giuseppe** [comment]
I am going to investigate this, it should not happen when runc is not installed

**Comment by giuseppe** [comment]
@miabbott I've pushed a PR here: https://github.com/projectatomic/atomic/pull/868
