### ISSUE TITLE
Understanding Systemd Scope in Project Atomic

### ISSUE THREAD

**Issue by kgrvamsi** [projectatomic/atomic#87]
I'm trying to configure kubernetes cluster on a 5 node project atomic nodes and when i want to change the system file of the kubectl it warns me that you can't change a readonly file even if i want to change as a root user.

So is the mount point of /etc/systemd mounts as ro(readonly) if so what can be a workaround to change the values inside the service files.

Thanks,
Vamsi

**Comment by ibotty** [comment]
What are you trying to do? If you want to change systemd unit files, that should work (you can use systemctl edit). Can you provide the atomic host version as well as the file you want to create/edit?

**Comment by rhatdan** [comment]
This is not related to the atomic command but to the atomic host.
