### ISSUE TITLE
atomic 1.15-2-1.fc25 is failing with atomic run command

### ISSUE THREAD

**Issue by kushaldas** [projectatomic/atomic#875]
Failed for me with the following error on F25 atomic host.
```
# atomic run kushaldas/busybox
'NoneType' object is not subscriptable
```
Going back to .14.1-1.fc25 made the above command working again.

**Comment by rhatdan** [comment]
Please output 
 atomic --debug run kushaldas/busybox

**Comment by baude** [comment]
Please try a more recent version and re-open if still not working.
