### ISSUE TITLE
Does atomic still use remote inspection via docker engine?

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic#898]
Notably, this patch:

http://pkgs.fedoraproject.org/cgit/rpms/python-docker-py.git/tree/remote-inspection.patch 

My brief search yielded it does not anymore. I'm assuming you are using skopeo for that now.

**Comment by baude** [comment]
@TomasTomecek correct!

**Comment by TomasTomecek** [comment]
Okay, so I will remove the patch from python-docker-2 (which I am planning to build in Fedora rawhide early next week)

**Comment by TomasTomecek** [comment]
This is now done in rawhide.
