### ISSUE TITLE
atomic scan incorrectly copies ostree content

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#916]
See https://github.com/ostreedev/ostree/pull/491#issuecomment-282802207

Looking at the code, I think there should be a `def get_transient_mountpoint_base()` defined per backend.  Then `syscontainers.py` can provide that as `return /ostree/repo/tmp/`, the docker backend can have it as `/run/atomic` as it is now.

scan would then combine the base with its chosen container names.

This would allow the ostree backend to do what it does best - create lots of hardlinks.

**Comment by baude** [comment]
Is there some subtlety I am not catching between /run/atomic and /ostree/repo/tmp ?  Can you elaborate?

Also, the mountpoint dir likely will need to be somewhat dynamic because multiple scans can occur simultaneously, so we can use a namedtemp dir or something for that.

**Comment by cgwalters** [comment]
They're on different filesystems.  `/run` is a tmpfs.  `/ostree/repo/tmp` is on the same physical filesystem as `/ostree/repo`, and hence `link()` works.

**Comment by cgwalters** [comment]
I understand the dynamic nature of the mountpoint directory.  I think the backend code should provide a *prefix*.  (That's what I meant with the `_base()` in the API but I wasn't clear enough)

**Comment by baude** [comment]
I'm working my way through this.  The first step is to perform the backend refactor for scan.py.

The next complicating problem is that atomic scan is designed around passing in an in dir that has a bunch of chroots mounted "inside it" (a dir of dirs).  If the backends are going to have different prefix'd mount points, it challenges that base rule and all the coding assumptions around it.  I think I can work around this but more or less recording it here so I remember it and make sure I deal with it.

**Comment by giuseppe** [comment]
I have some WIP here:

https://github.com/projectatomic/atomic/pull/917

It is WIP as I have not really tested it well.  As we don't really have the mount logic in the new backend stuff, I've worked directly in scan.py and mount.py.
