### ISSUE TITLE
help: prefer file over label

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic#939]
On our recent Fedora activity day, we decided that we would prefer atomic command to pick file in a container over label. Right now it's the other way around, label is preferred over file.

Would you be interested in such changes? If so, I will send a PR.

https://pagure.io/atomic-wg/issue/256

**Comment by rhatdan** [comment]
I am fine with this,  @baude WDYT?

The only problem I would see with this would be if someone wanted to add a layer onto a the container they would need to replace the file, if they wanted to change the help.

**Comment by TomasTomecek** [comment]
> The only problem I would see with this would be if someone wanted to add a layer onto a the container they would need to replace the file, if they wanted to change the help.

Or they can remove it. Yes it will leak in layers, but won't be present in container.

I think all metadata suffer from that issue: if you don't update them, you get them from base image. E.g. for labels this may get really confusing.

**Comment by rhatdan** [comment]
Submit a pull request.
