### ISSUE TITLE
Dockerfile label capitalization issues

### ISSUE THREAD

**Issue by yuqi-zhang** [projectatomic/atomic#948]
It was recently highlighted during a fedora atomic wg meeting that there are some discrepancies in the capitalization of labels in Dockerfiles (https://pagure.io/atomic-wg/issue/253):

1. Some places have capitalized first characters (e.g. Name=mycontainer), such as the current examples given in https://fedoraproject.org/wiki/Container:Guidelines#LABELS, and it is being used in the rhel containers such as: https://github.com/aveshagarwal/etcd-container/blob/master/Dockerfile

2. The generic labels guideline in our repo: https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md uses all lower case instead, as well as official docker documentation.

3. In the atomic command line, "INSTALL" "UNINSTALL" and "RUN" are specifically all capitalized.

I think it would be a good way to somehow consolidate this, so all containers can follow a specific guideline on this. Since the all lower case seem to be the standard, should the atomic CLI be modified to accept "install", "uninstall", "run" instead? Or should those be special cases? I'm not too familiar with the history of this.

Thoughts? @rhatdan @baude @aveshagarwal @giuseppe

**Comment by rhatdan** [comment]
https://github.com/projectatomic/ContainerApplicationGenericLabels should be the standard.
