### ISSUE TITLE
Label 'help' in the Fedora Guidelines and in the Atomic tool

### ISSUE THREAD

**Issue by hhorak** [projectatomic/atomic#967]
This is a cross-posting of https://pagure.io/atomic-wg/issue/267, so it gains some attention of atomic tool guys.. Please, use the pagure ticket for the discussion.

**Comment by TomasTomecek** [comment]
Related: https://github.com/projectatomic/atomic/issues/939

**Comment by TomasTomecek** [comment]
@hhorak can we close? all related atomic WG issues are closed.

**Comment by hhorak** [comment]
Sure.
