### ISSUE TITLE
syscontainers: Avoid requiring rpmbuild

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#981]
See http://pkgs.fedoraproject.org/cgit/rpms/atomic.git/commit/?id=8c4a38a7f187c45926bdf60ae937f7a6090cbeae
:arrow_right: https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2017-April/msg00059.html

I haven't looked, but offhand, I suspect it won't be that hard to construct a binary RPM without doing a "build".

**Comment by giuseppe** [comment]
we allow containers to provide a customized `.spec` file.  Should we limit this for now and allow only the arbitrary copy of files to the host?  We could probably take the metadata for dependencies/conflicts (which is probably the only part that is really useful) from the image labels as we already do in case a spec file is not specified.

@rhatdan @ashcrow @TomasTomecek

**Comment by TomasTomecek** [comment]
I propose to raise this issue with Software Management team. I personally dislike constructing binary RPMs using some hacky method - this could lead into some unpredictable behavior (does RPM software keep binary RPMs compatible?).

**Comment by baude** [comment]
how about building from within a container?

**Comment by giuseppe** [comment]
we would require to create a container everytime we want to install a container that exports files, I think this feature should be lower level than that and be better tied to the system.  I like the idea of Colin to have a `lightweight rpmbuild` that only packs these files into an .rpm.  We probably don't need to support the build from a `.spec` file part we have now and only a small subset.

**Comment by baude** [comment]
Given that atomic packages would appear broken with the removal of rpmbuild, can we come up with something quickly? I'm willing to help if others are limited on time.

**Comment by giuseppe** [comment]
the best short term fix is probably to not require rpmbuild and not create the rpm when it is not present, in this case we can still copy files to the host but we will not track them with an .rpm file (which is already implemented as fallback). What do you think?

**Comment by rhatdan** [comment]
Can we open up a discussion with the rpmbuild maintainers to see if we can get the lightweight rpmbuild.

**Comment by rhatdan** [comment]
I agree with the fallback to no rpmbuild for now, when it is not present.

**Comment by giuseppe** [comment]
I played a bit with it and this looks the minimal implementation I could get for building an RPM out of a tree directory:

https://gist.github.com/giuseppe/43cdb1e86f3042c4bcfd25cb68a249af

It still miss some pieces we need, but it is already able to build an rpm that `rpm -i` accepts

**Comment by giuseppe** [comment]
I've cleaned it a bit up and moved here:

https://github.com/giuseppe/tinyrpmbuild

Would something like that work?  I think it is fine to drop support for specfiles and avoid the build of the .rpm.  If something more advanced is required a prebuilt rpm can be included in the container.

**Comment by cgwalters** [comment]
I'd say we should go with it.
