### ISSUE TITLE
need a way to skip the y/n prompt when removing images/containers

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic#985]
It appears there is no way to skip the y/n prompt when using `atomic images delete` or `atomic containers delete`.

This makes automating the use of the `atomic` tool for cleaning up the images/containers a bit more difficult.

I envision something like this:

```
# atomic images delete -y --all
#
# atomic containers delete -y --all
#
```

**Comment by yuqi-zhang** [comment]
I think what you want is `atomic --assumeyes images delete`

**Comment by miabbott** [comment]
Yup, that's what I want.  Thanks!
