### ISSUE TITLE
atomic host + docker-machine + digital ocean

### ISSUE THREAD

**Issue by klud1** [projectatomic/atomic#988]
I'm facing a problem with docker-machine and fedora atomic on Digital Ocean, when trying to create a machine via `docker-machine create node1 -d digitalocean --digitalocean-access-token XXX-XXX --digitalocean-image fedora-25-x64-atomic` it can't provision docker since yum is not present in atomic host.

the `docker-machine` command outputs the following error:
```
Running pre-create checks...
Creating machine... (manager)
Creating SSH key... (manager)
Creating Digital Ocean droplet... (manager)
Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with fedora...
Error creating machine:
Error running provisioning: something went wrong running an SSH command
command : sudo -E yum install -y curl
err : exit status 1
output : sudo: yum: command not found
```

**Comment by rhatdan** [comment]
This repo is for the atomic cli, you really want this for the atomic host.

@cgwalters PTAL

**Comment by miabbott** [comment]
@dustymabe You might be interested in this, too

**Comment by dustymabe** [comment]
hey @klud1 - thanks for reaching out - I responded to [your comment](http://www.projectatomic.io/blog/2017/04/fedora-atomic-digitalocean/) on the blog post. basically *curl is already installed in atomic host so this command should not be needed. Unfortunately docker machine doesn't seem to handle that case. Perhaps we could open a bug against that git repo to add support.*

A while back @cdrage was [working on adding support](https://github.com/cdrage/machine/commit/80de5fc46cdeae5a852baac5c1d63b734fcf0034) to that project to support atomic host. I've asked him if he would pick up his work and try to get it merged.

**Comment by klud1** [comment]
Oh, @rhatdan, so sorry, my mistake.

@dustymabe, thanks for your response, just saw it, been off for some days. I'm opening an issue on their repo then.

Thanks for the help, guys!

**Comment by dustymabe** [comment]
@klud1 if you don't mind mention me in that issue or link it back here so I can track it.

**Comment by klud1** [comment]
@dustymabe sure, no problem.

**Comment by baude** [comment]
can we close this please?

**Comment by rbucker** [comment]
still does not work
